### PR TITLE
Caddyfile reverse_proxy example

### PR DESCRIPTION
**Pull request by serafdev**
Added a Caddy reverse_proxy example

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Comment by l3miage-pelletl** [comment]
I think this is better:
```
subdomain.example.com {
        rewrite /.well-known/carddav /remote.php/dav
        rewrite /.well-known/caldav /remote.php/dav
        reverse_proxy localhost
}
```

**Comment by serafdev** [comment]
I agree @l3miage-pelletl that looks much better, thank you!

**Pull request merged**
