### PR TITLE
[stable9] update supported apps

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @karlitschek @jospoortvliet @nickvergessen @oparoz

### CODE REVIEW

**Comment by nickvergessen** [comment]
LGTM

**Comment by mar1u5** [comment]
LGTM

**Comment by nickvergessen** [comment]
Theming here as well

**Comment by mar1u5** [comment]
Already done :wink: https://github.com/nextcloud/documentation/pull/84 @nickvergessen

**Pull request merged**
