### PR TITLE
fix HSTS header in nginx subdir configuration

### PR DESCRIPTION
**Pull request by fdiwald**
Headers defined in a specific section are overwritten if there are additional headers defined in a subsection. This is true for the header for HSTS (`Strict-Transport-Security`) in the `server` section which is overwritten by the headers in the `location ^~ /nextcloud` section. This is documented in the [nginx documentation](http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header).
This solution only sends the header for the nextcloud-subdir. I guess it would be more correct to set the header for all locations but I did not find an elegant solution to that problem. Maybe an nginx pro could come up with a better solution.
Signed-off-by: Florian Diwald <fdiwald@hotmail.com>

### CODE REVIEW

**Comment by Tachi107** [comment]
> This solution only sends the header for the nextcloud-subdir. I guess it would be more correct to set the header for all locations but I did not find an elegant solution to that problem.

What about just adding `add_header` in both sections? May not be elegant, but an imperfect solution is better than no solution at all :)

**Comment by fdiwald** [comment]
Correct. This is the consequence of my approach. If you add a directory (for instance `/collabora`) you should add the headers there too.

**Comment by ChristophWurst** [comment]
Conflicts, unfortunately

**Comment by fdiwald** [comment]
@ChristophWurst is there still something I have to fix or is this pull request ready for review? Honestly, I am a bit overwhelmed by the checks here. Not sure what they mean.

**Comment by ChristophWurst** [comment]
It should be fine

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
