### PR TITLE
Add fail2ban hardening

### LINKED ISSUE #1295: Add fail2ban configuration documentation
add fail2ban configuration documentation
refference link:
https://github.com/nextcloud/vm/blob/master/apps/fail2ban.sh

### PR DESCRIPTION
**Pull request by eibex**
Adds a fail2ban section to the hardening page in the admin manual.

It includes filters and jails for ~~both~~ Nextcloud ~~and the sshd service~~.

Nextcloud filters were based off the ones used in nextcloudpi as shown [here](https://github.com/nextcloud/nextcloudpi/commit/c0cee6bce659960d1c92b305296439ed6f0c6d44), with the addition of trusted domains checks. The proposed regex wouldn't work on Nextcloud 17 or older (i.e. NC 18+ only).

I also modified the wrapping of one of the previous paragraphs to match the 80 column limit as mentioned in the repository's README.

This is my first contribution to any project's documentation and feedback is more than welcome.

Would close #1295

Signed-off-by: Eibe <40539455+eibex@users.noreply.github.com>

### CODE REVIEW

**Comment by eibex** [comment]
I am unsure if sshd jails fit the scope of Nextcloud's documentation. I could remove them if necessary.

**Comment by MorrisJobke** [comment]
> I am unsure if sshd jails fit the scope of Nextcloud's documentation. I could remove them if necessary.

I would say that we should only document Nextcloud specific entries. For sshd their documentation is a better location IMO.



> This is my first contribution to any project's documentation and feedback is more than welcome.

And it looks really nice 👍 Thank you for this :)

**Comment by eibex** [comment]
Removed sshd section

**Comment by eibex** [comment]
Sorry for force pushing again. I noticed I used "webserver" instead of "Web server" in one of the paragraphs. Changed it for consistency as mentioned in the README.

**Pull request merged**
