### PR TITLE
Document the login name during the login flow

### PR DESCRIPTION
**Pull request by MorrisJobke**
@rullzer @tobiasKaminsky Please finish

Ref https://github.com/nextcloud/server/issues/7593#issuecomment-364213844

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
We on Android are getting it via "/ocs/v1.php/cloud/user and then use value of "id".

```
<?xml version="1.0"?>
<ocs>
	<meta>
		<status>ok</status>
		<statuscode>100</statuscode>
		<message>OK</message>
		<totalitems></totalitems>
		<itemsperpage></itemsperpage>
	</meta>
	<data>
		<enabled>1</enabled>
		<id>tobi</id>
		<storageLocation>/srv/http/nc/data/tobi</storageLocation>
		<lastLogin>1530685927000</lastLogin>
		<backend>Database</backend>
		<subadmin/>
		<quota>
			<free>169801994240</free>
			<used>5637339567</used>
			<total>175439333807</total>
			<relative>3.21</relative>
			<quota>-3</quota>
		</quota>
		<email>test@test.de</email>
		<phone>123</phone>
		<address>123</address>
		<website></website>
		<twitter></twitter>
		<groups>
			<element>admin</element>
			<element>group</element>
		</groups>
		<language>en</language>
		<locale></locale>
		<display-name>Tobias K</display-name>
	</data>
</ocs>
```

I do not know if there is something better/easier.

So, we want to use loginname vs username? I am fine with this, but username is internally/in ocs named "id", which is a different naming (again).

**Comment by MorrisJobke** [comment]
Sure :) On my list for a long time already.

**Comment by MorrisJobke** [comment]
@skjnldsv Done :)

**Pull request merged**
