### PR TITLE
Add some docs for developers wanting to the OCS and the AppFramework

### PR DESCRIPTION
**Pull request by rullzer**
CC: @MorrisJobke @nickvergessen @LukasReschke 

I doubt it is used much. But better to update the docs a bit.

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by nickvergessen** [comment]
Is this in 10 as well?

**Comment by nickvergessen** [comment]
Also please post in https://help.nextcloud.com/c/dev/app-dev

**Comment by rullzer** [comment]
so a part of it is in 10. But some stuff is missing that I don't want to backport. So I'd say leave it only in 11 and don't hit at 10 devs that they have to change already.

**Pull request merged**
