### PR TITLE
Updated Android developer documentation to reflect the actual state

### PR DESCRIPTION
**Pull request by AndyScherzinger**
PR resolving #12 - fixing all links, removing Eclipse and adding Gradle + Git submodule for using the library project

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Looks good 👍 (I didn't tested this, but reading it looks fine)

**Comment by AndyScherzinger** [comment]
So merge then or wait for a second review? Just asking since I am not sure if documentation also has a 2 person review process. :)

**Comment by mar1u5** [comment]
I am the 2nd one 😈 Merging.

**Comment by MorrisJobke** [comment]
> So merge then or wait for a second review? Just asking since I am not sure if documentation also has a 2 person review process. :)

@AndyScherzinger For documentation one person is enough ;)

**Pull request merged**
