### PR TITLE
Fix more stuff

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @LukasReschke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Easiest to be reviewed like this: https://github.com/nextcloud/documentation/pull/72/files?w=1

**Comment by MorrisJobke** [comment]
Needs a forwardport to master

**Comment by nickvergessen** [comment]
:-1:

**Comment by nickvergessen** [comment]
Let's do https://github.com/nextcloud/documentation/pull/76 first, solves some of the issues and is a mass to redo

**Comment by MorrisJobke** [comment]
> Let's do #76 first, solves some of the issues and is a mass to redo

yep. I know. we have worked on this in parallel.

**Pull request merged**
