### PR TITLE
Fixed several typos and grammar errors

### PR DESCRIPTION
**Pull request by AndrewDawes**
Found and fixed several typo and grammar errors :-)

### CODE REVIEW

**Comment by kesselb** [comment]
Hi, thanks for your pull request. Please sign off your commits.

To add your Signed-off-by line to every commit in this branch:

- Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
- In your local branch, run: git rebase HEAD~1 --signoff
- Force push your changes to overwrite the branch: git push --force-with-lease origin fix_typos

**Comment by AndrewDawes** [comment]
Hi @kesselb, signed off now

**Review by kesselb — APPROVED** [review]
Thank you

**Pull request merged**
