### PR TITLE
Fix configuration parameters description

### PR DESCRIPTION
**Pull request by christianlupus**
The example configuration in the admin docs is currently not ideally structured. Some information pieces are in the wrong section.

This PR tries to move some information into the corresponding action and also to fix some minor syntax issues in the file.

### CODE REVIEW

**Comment by kesselb** [comment]
Hey, thanks for your pull request.

The section is auto-generated from https://github.com/nextcloud/server/blob/master/config/config.sample.php

**Comment by kesselb** [comment]
Hi @christianlupus, please send a pull request to https://github.com/nextcloud/server/ to update the description.

**Comment by christianlupus** [comment]
Hi, @kesselb, I just opened the PR nextcloud/server#35881 to fix this upstream. I cannot test the output currently, as I have not found a way to simulate the auto-generation locally. Can you hint me to a script/program/... to extract the documentation? This would allow me to fix the missing part of the documentation.

Thank you very much!

**Comment by kesselb** [comment]
Hi, please have a look at: https://github.com/nextcloud/nextcloud-config-converter

**Comment by christianlupus** [comment]
Ok, thanks. That helped me to fix one more issue with my changed in the server pr.

**Pull request closed without merging**
