### PR TITLE
Add documentation for cache control immutable

### PR DESCRIPTION
**Pull request by CarlSchwan**
See https://github.com/nextcloud/server/pull/31141

I didn't test it, can an nginx expert try to see if the syntax is correct?

Signed-off-by: Carl Schwan <carl@carlschwan.eu>

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Looks good

**Comment by CarlSchwan** [comment]
> This didn't work for me. Adding the directive resulted in 404s for urls like `https://example.org/css/core/88a4-d75f-server.css?v=36d57b3bd263334af5e8ac7e29611776-a53c3031-7` and thus no CSS being loaded.
> 
> This is a pretty vanilla setup, [using docker](https://github.com/nextcloud/docker) and `nginxproxy/nginx-proxy` in front of the app and I'm basically using the documentation's nginx-config 1:1. Highly possible that I'm doing something wrong here, but I still wanted to let you know.

Thanks for the feedback, I will look into ut tomorrow

**Comment by icewind1991** [comment]
Did some more testing and I can reproduce, I think I placed the block in a different place when testing initially :see_no_evil: 

Adding the `try_files $uri /index.php$request_uri;` line to the new location block fixes things for me

**Comment by MichaIng** [comment]
This is a general "issue" with Nginx, not all directives present in the parent location block are inherited. AFAIK this affects `location ~ \.wasm$ {` as well regarding e.g. the cache control header which should currently not apply to these.

Are there actually assets without versioned query string? Otherwise we could just merge it by appending `(\?v=.*)` to the parent. Directly defining the `Cache-Control` header seems more reasonable anyway compared to using `expires 6M;` as another layer of abstraction which sets/implies a few other things we may not want, depending on Nginx version as well.

**Pull request merged**
