### PR TITLE
add Content-Security-Policy header

### PR DESCRIPTION
**Pull request by morgankevinj**
Add "add_header Content-Security-Policy "default-src 'self'" always;" and remove redundant headers

### CODE REVIEW

**Comment by skjnldsv** [comment]
Hi,

Our csp settings are managed within nextcloud directly.


> remove redundant headers

What do you mean by that?

**Comment by morgankevinj** [comment]
Setting frame-ancestors to 'none' should be roughly equivalent to X-Frame-Options: DENY.
script-src limits scripts so it can replace X-XSS-Protection.
When frame-ancestors and script-src are not decaled the policy fallsback on default-src.
according to https://content-security-policy.com/#source_list

**Comment by skjnldsv** [comment]
cc @rullzer

**Comment by rullzer** [comment]
Nope. We set the csp from nextcloud. Because we need to also set the nonce etc.

**Comment by kesselb** [comment]
Thanks @morgankevinj :+1: 

Unfortunately IE11 is still supported https://github.com/nextcloud/browserslist-config/blob/master/browserlist.config.js

and does not support the frame-ancestors directive https://caniuse.com/#feat=mdn-http_headers_csp_content-security-policy_frame-ancestors

**Comment by skjnldsv** [comment]
Closing then :)

**Pull request closed without merging**
