### PR TITLE
Fixed URL

### PR DESCRIPTION
**Pull request by rakekniven**
Reported at Transifex.

Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>

### CODE REVIEW

**Comment by silopolis** [comment]
👌

**Comment by nickvergessen** [comment]
I think we should add a redirect instead or additionally.

**Comment by nickvergessen** [comment]
Don't think that's possible, the translations can replace the URL.
But links from older untranslated versions should be mapped to existing pages

**Review by tflidd — APPROVED** [review]

**Comment by tflidd** [comment]
I just approved the change to get it corrected. To have links within the language is a more general topic I suppose....

**Pull request merged**
