### PR TITLE
Remove APC config line from Redis example

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by skjnldsv** [comment]
Any reasons?
It's here on purpose iirc!

**Comment by szepeviktor** [comment]
Oh! I see.

**Comment by skjnldsv** [comment]
@szepeviktor what motivated you to remove this from the documentation? Did you experienced something specific?

**Comment by szepeviktor** [comment]
@skjnldsv I thought it was a copy&paste leftover from the APC section.

**Comment by skjnldsv** [comment]
Ah!
Not that I'm aware of :)

Thanks for your help!!

**Pull request closed without merging**
