### PR TITLE
Modernize user facing WebDAV doc overview (round one)

### PR DESCRIPTION
**Pull request by joshtrichards**
* Try to make it more approachable
* Preparation and baby steps towards some modernizing
* Boost recommendation for app password use when using third-party WebDAV clients[1]

[1] https://github.com/nextcloud/server/issues/32729#issuecomment-1548181344 

https://github.com/nextcloud/server/issues/32729#issuecomment-1556667151

Mostly moved some things around for clarity and tweaked some wording here and there.

I have at least one more commit before considering this "done" from my perspective: mostly to clean up link references (and likely typos). Sharing early in case anyone feels like providing any early feedback.

### ☑️ Resolves

* Fix nextcloud/server#32729 (in part)

### 🖼️ Screenshots

Screenshot 2023-05-25 at 22-54-31 Accessing Nextcloud files using WebDAV — Nextcloud latest User Manual latest documentation

### CODE REVIEW

**Comment by kesselb** [comment]
Added screenshot.

**Review by kesselb — APPROVED** [review]
Thanks a lot!

**Comment by joshtrichards** [comment]
Calling this round done for now. Don't want to deal with any more merge conflicts (my fault for sitting on this a few days longer than I'd hoped). Merge at your discretion.

P.S. I can't fully squash this because there was a temporary merge conflict (unless there is some clever way of still squashing after resolving a conflict I'm unaware of).

**Comment by joshtrichards** [comment]
If the extra commit from the `master` merge due to doing the conflict resolution via GitHub is an issue let me know and I'll pull this down and redo it locally.

**Pull request merged**
