### PR TITLE
add Talk documentation

### PR DESCRIPTION
**Pull request by jospoortvliet**
Replacing/superseding https://github.com/nextcloud/documentation/pull/6883
Signed-off-by: Jos Poortvliet <jospoortvliet@gmail.com>

### CODE REVIEW

**Review by marcoambrosini — APPROVED** [review]

**Comment by jospoortvliet** [comment]
should we backport (I think at least to 21 and 20) - then, how?

**Comment by jospoortvliet** [comment]
I realize not all features are fully available in those releases but most of it is still very helpful I'd say...

**Comment by nickvergessen** [comment]
> I realize not all features are fully available in those releases but most of it is still very helpful I'd say...

just link the people to latest/ then? Better then having docs for non existing features?

**Comment by jospoortvliet** [comment]
> > I realize not all features are fully available in those releases but most of it is still very helpful I'd say...
> 
> just link the people to latest/ then? Better then having docs for non existing features?

For 22 it makes sense to merge, probably also for 21 - everything is there, I believe, or maybe 1 or 2 small things missing. For 20, I don't know - you probably know if there's really much missing.

**Comment by skjnldsv** [comment]
Emoji break pdf, removed in #6923

**Comment by jospoortvliet** [comment]
Sorry, brittle stuff huh, didn't know emoji's don't work.

**Pull request merged**
