### PR TITLE
Added support for Built-in CODE Server (ARM64)

### PR DESCRIPTION
**Pull request by dgiebert**
Needed to support the arm64 Code Server, also used here https://github.com/nextcloud/helm/pull/540

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]

**Comment by joshtrichards** [comment]
Holy crap! How did we overlook this? Thanks for fixing this! 

Best as I can tell, way back in #2197 the arm64 handling was noted, but the legacy routes were removed outright so it was a non-issue, but then when #7141 added back the legacy route handling it got overlooked.

I've looked at that config probably hundreds of times. :disappointed: 

Needs to be added here too in (via the same PR or one immediately following): https://github.com/nextcloud/documentation/blob/4eca582c9e337e53edace0d872973d1abb2dcaf8/admin_manual/installation/nginx-root.conf.sample#L145

**Review by provokateurin — CHANGES_REQUESTED** [review]
@joshtrichards thanks for catching this, it needs to be fixed in both config files.

**Review by provokateurin — APPROVED** [review]

**Pull request merged**
