### PR TITLE
Add .drone.yml for basic documentation build

### PR DESCRIPTION
**Pull request by juliushaertl**
https://github.com/nextcloud/documentation/issues/3

By now this is just running make html-all for admin_manual, developer_manual, user_manual
Requires: https://github.com/nextcloud/docker-ci/pull/8

Maybe adding further steps like linkcheck / rst-lint would also make sense? @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@juliushaertl Looks nice :) I will test this tomorrow.

@LukasReschke What about actively deploying the changes to our docs server instead of having the cron job run every night? ;)

**Comment by MorrisJobke** [comment]
I created the automated build on docker hub and enabled drone for this repo. Let's see :)

**Comment by rullzer** [comment]
@MorrisJobke indeed. Drone should be awesome for this... What would be (IMO ideal)

1. sanity check (or whatever we do)
2. build docs and deploy to temp location (for easy review and seeing the stuff)
3. On merge
  * Delete temp stuff
  * Deploy to docs page right away

**Comment by MorrisJobke** [comment]
The build passed -> Let's merge this and improve it step by step

**Pull request merged**
