### PR TITLE
occ command to reset bruteforce attempts

### PR DESCRIPTION
**Pull request by hellfi**
adding documentation regarding #20005 Implement occ command to reset bruteforce attemps from a given IP address 
functionality is already implemented

### CODE REVIEW

**Comment by rakekniven** [comment]
Hello @hellfi ,

just seen your PR and the occ command you mentioned is not part of the shipped server package (bundled apps)

This is from app BruteForceSettings (https://github.com/nextcloud/bruteforcesettings), or?

**Comment by hellfi** [comment]
@rakekniven 
I think https://github.com/nextcloud/server/blob/master/core/Command/Security/ResetBruteforceAttempts.php is part of the server package

**Comment by rakekniven** [comment]
> I think https://github.com/nextcloud/server/blob/master/core/Command/Security/ResetBruteforceAttempts.php is part of the server package

You are right. Good catch.

**Review by rakekniven — APPROVED** [review]

**Comment by rakekniven** [comment]
Hello @hellfi ,

I highly appreciate your help here. Please set your dco https://github.com/apps/dco for your next contribution.

**Pull request merged**
