### PR TITLE
change to cardbook instead of Sogo

### PR DESCRIPTION
**Pull request by enoch85**
Fixes https://github.com/nextcloud/documentation/issues/529

https://github.com/nextcloud/documentation/blob/cardbook/user_manual/pim/sync_thunderbird.rst

### CODE REVIEW

**Comment by enoch85** [comment]
@zorck97 can you please review this PR I made? Thanks!

**Comment by enoch85** [comment]
Please squash the commits when merging, thank you!

**Comment by MorrisJobke** [comment]
stable12 ed451efe

**Comment by enoch85** [comment]
Thanks @MorrisJobke

**Pull request merged**
