### PR TITLE
add command to get user DN

### PR DESCRIPTION
**Pull request by enoch85**
I always forget, so better add it to the docs :)

cc @blizzz

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by blizzz** [comment]
It's an AD specific client tool. So far we don't have any hint to use any client tool to figure out this or that in this documentation page. If we start with it, we need to add examples for ldap-utils (ldapsearch command etc.), too (which are at least server agnostic), and would extend this page further. 

I would prefer if we either have a link to one or two cheat sheets that handle AD tools and ldap-utils or a seperate page were we would have some tips on these tools.

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket.
If you wish to resume your work on this, please re-open.

**Comment by enoch85** [comment]
I would prefer to leave this open, if not @blizzz thinks it will never be implemented? With the reasoning above maybe this could be the first command, to add more later?

**Comment by skjnldsv** [comment]
I'll let you two decide on what do to with that :)

**Comment by blizzz** [comment]
No, i don't want to fill it up for commands of every possible client tool out there :) I am good with one of those options (in that order):

* link to cheat sheets instead
* only examples for a server agnostic tool
* have a different page for 3rd party clients.  
 
But that's really not something covering Nextcloud but the flavour of LDAP being used.

**Comment by juliushaertl** [comment]
@enoch85 Mind to adjust this to one of the proposed ways?

**Comment by enoch85** [comment]
I'm OK with closing this, I will find it here anyway. :)

**Pull request closed without merging**
