### PR TITLE
Add note about dependency limitation for apps

### PR DESCRIPTION
**Pull request by AndyScherzinger**
... with respect to supporting Nextloud server versions.

### CODE REVIEW

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
`dependencies/php`, `dependencies/database` and `dependencies/lib` should be noted to not have any effect. Once info.xsd is updated to remove these xml elements we should drop their documentation here

**Comment by AndyScherzinger** [comment]
@ChristophWurst better this way?

**Comment by nickvergessen** [comment]
> dependencies/database … should be noted to not have any effect. Once info.xsd is updated to remove these xml elements we should drop their documentation here

database is needed, to indicate oracle as supported or not (most community apps don't). It is also okay to support more databases going forward, but you can not drop any basically.

And e.g. specifying DBs but not oci will allow you to bypass column lengths and other things:
https://github.com/nextcloud/server/blob/d151999fc8f31f7c9e76e9aa07a0ca50a9d5bdd6/lib/private/DB/MigrationService.php#L84-L96

**Comment by nickvergessen** [comment]
> Do we have a way to deprecate them else when dropped any use would be "illegal" while I can't tell if we actually schema-validate the info.xml

If we remove them from the XSD all apps will break and you can no longer upload to the appstore. So not sure we want to do that. At least not now.
I think we should talk about this at the next occasion instead and draft a proper plan.
But mostlikely it makes sense to just keep them (at least database and lib) and just make sure authors understand that it can break things on updates if you change requirements and they don't cover the stock anymore.

**Comment by ChristophWurst** [comment]
Then let's do like any other API removal

1) Make it a noop and mention it in the upgrade docs of 26 and on the metadata page
2) Remove it in the 26+3=Nextcloud 29 release

**Comment by AndyScherzinger** [comment]
In any way, fine to merge @nickvergessen @ChristophWurst ?

**Review by nickvergessen — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
