### PR TITLE
feat(developer_manual): add vue l10n hint

### PR DESCRIPTION
**Pull request by skjnldsv**
image

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
*now

Yes

**Comment by nickvergessen** [comment]
https://app.transifex.com/nextcloud/nextcloud/translate/#de_DE/forms/292968597?q=text%3Arequired

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/docker-ci/pull/619

**Comment by skjnldsv** [comment]
> Hey John and Joas,
> 
> really appreciated.

🤗🤗🤗

**Pull request merged**
