### PR TITLE
feat(dev-manual): Warn about the upcoming PSR-0 class loader removal

### PR DESCRIPTION
**Pull request by ChristophWurst**
For https://github.com/nextcloud/server/pull/36114

Bildschirmfoto vom 2023-01-13 13-22-54

### CODE REVIEW

**Comment by PVince81** [comment]
please also post a link to the forum once deployed

**Comment by AndyScherzinger** [comment]
For the forum post please elaborate a bit with pointer about how the migration would look like, extra points for examples (in Nextcloud apps)

**Comment by nickvergessen** [comment]
The forum will get it with the final cross post of the critical changes list?

**Comment by nickvergessen** [comment]
Posted to https://github.com/nextcloud/server/issues/34692

**Comment by ChristophWurst** [comment]
https://help.nextcloud.com/t/breaking-removal-of-psr-0-class-loader-in-nextcloud-27/153916

**Pull request merged**
