### PR TITLE
link to portal.

### PR DESCRIPTION
**Pull request by jospoortvliet**
Signed-off-by: Jos Poortvliet <jospoortvliet@gmail.com>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Backport is in #655

**Comment by J0WI** [comment]
Please consider reverting this change. The portal article does not cover all previously documented topics.

**Comment by MorrisJobke** [comment]
> Please consider reverting this change. The portal article does not cover all previously documented topics.

What exactly is missing here?

**Comment by dagguh** [comment]
Hiding docs beyond a paywall violates [Nextcloud's principle](https://nextcloud.com/about/) of open source.

[Quoting](https://karlitschek.de/2016/04/big-changes-i-am-leaving-owncloud-inc-today/) @karlitschek:
> And what matters more, short term money or long term responsibility and growth?

Multi-machine deployments are not just for big enterprises. I'm self-hosting a Nextcloud instance for my family. Convincing people to ditch Google is hard enough already, but if I cannot guarantee high availability... One power shutdown or ISP fail and nobody will want to reclaim their data again, too much inconvenience. My brother wants to help, by co-hosting another instance at the family house. But [setting up a distributed instance is full of traps and gotchas](https://bayton.org/blog/2017/06/experimenting-with-clustering-and-data-replication-in-nextcloud-with-mariadb-galera-and-syncthing/).

**Pull request merged**
