### PR TITLE
clarified trash bin retention by storage shortage override

### PR DESCRIPTION
**Pull request by wiswedel**
Signed-off-by: Sascha Wiswedel <sascha.wiswedel@nextcloud.com>

### CODE REVIEW

**Comment by wiswedel** [comment]
note: There are internal links which are pointing to /latest/. @juliushaertl shall we adjust that in backports or just leave it that way? I'd say let's leave it so we don't have to update it with each release.

**Comment by skjnldsv** [comment]
> note: There are internal links which are pointing to /latest/. @juliushaertl shall we adjust that in backports or just leave it that way? I'd say let's leave it so we don't have to update it with each release.

fine to leave latest I think

**Pull request merged**
