### PR TITLE
docs: fix duplicated DB command and add missing

### PR DESCRIPTION
**Pull request by JanMalte**

### CODE REVIEW

**Review by tflidd — APPROVED** [review]
Looks good, however only the missing indices are documented to be used with the occ command:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
> however only the missing indices are documented to be used with the occ command:

I guess that is another thing to update

**Pull request merged**
