### PR TITLE
Simple typo fix in documentation to cd into directory

### PR DESCRIPTION
**Pull request by stalker314314**

### CODE REVIEW

**Comment by stalker314314** [comment]
@juliushaertl Hi, is there anything I can do to push this faster? Seems some checks are failing, but not sure they are related to my change?

**Comment by juliushaertl** [comment]
@stalker314314 Can you rebase your branch to current master? That should fix the failing CI.

**Comment by stalker314314** [comment]
Thanks:)

**Comment by MorrisJobke** [comment]
I fixed the commits in here for you. Now it looks good 👍

**Comment by MorrisJobke** [comment]
stable13 3e96f352
stable12 b650cb38

**Pull request merged**
