### PR TITLE
fix(developer): Generate icon docs again

### PR DESCRIPTION
**Pull request by nickvergessen**
### ☑️ Resolves

Together with this beauty: https://github.com/nextcloud/server/pull/39811 this helps to generate the icon docs again

### 🖼️ Screenshots

grafik

### CODE REVIEW

**Review by skjnldsv — CHANGES_REQUESTED** [review]
They're deprecated, so I still think we should not have them.
Didn't they got removed on purpose?

**Comment by nickvergessen** [comment]
No, the generating code broke with the change from scss to compiling with node sass.

We can also add a deprecation warning, fine by me. I'm just trying to get rid of the warning/error so we can enable https://github.com/nextcloud/documentation/pull/10984

The missing file is still referenced in https://github.com/nextcloud/documentation/blob/master/developer_manual/html_css_design/icons.rst?plain=1#L15

So either we remove the full block, or we fix the docs by generating the file again

**Comment by skjnldsv** [comment]
I'm up for removal, especially with 28

**Comment by nickvergessen** [comment]
Removal part of https://github.com/nextcloud/documentation/pull/10984

**Pull request closed without merging**
