### PR TITLE
Update screenshots in user manual

### LINKED ISSUE #341: Update screenshots in user manual
There are some old screenshots mentioning oc: https://docs.nextcloud.com/server/12/user_manual/files/access_webdav.html

maybe @MariusBluem can help out here :)

### PR DESCRIPTION
**Pull request by MariusBluem**
This PR will fix #341 - once it is finished 😅 
@MorrisJobke 

Signed-off-by: Marius Blüm <marius@lineone.io>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
You rock 🚀

**Comment by MariusBluem** [comment]
Question: Are the screenshot rendered in their size or must they be in any correct format 🤔 @MorrisJobke

**Comment by MorrisJobke** [comment]
> Question: Are the screenshot rendered in their size or must they be in any correct format 🤔 @MorrisJobke

They are rendered with a max-width:100% ... so it should be fine to make them bigger ;)

**Comment by MariusBluem** [comment]
Will do. Windows and Gnome today 💪

**Comment by MariusBluem** [comment]
OK ... Screenshots are adjusted now. Gnome does not need one, Windows 7 is fine with me :)
_Note: Please check DAV in Dolphin - did not work for me_

Please review @MorrisJobke

**Comment by MorrisJobke** [comment]
stable11 #369

**Comment by MorrisJobke** [comment]
stable10: #370

**Pull request merged**
