### PR TITLE
Changed mysqldump parameter to close #375

### LINKED ISSUE #375: Backing up Nextcloud - mysqldump parameter
Hi everyone,

the article [Backing up Nextcloud](https://docs.nextcloud.com/server/11/admin_manual/maintenance/backup.html#backup-database) suggests the following command for backing up the MySQL tables using mysqldump (shortened):

`mysqldump --lock-tables -h [server] -u [username] -p[password] [db_name]`

The [official mysqldump documentation](https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_lock-tables) states the following:

> For transactional tables such as InnoDB, --single-transaction is a much better option than --lock-tables because it does not need to lock the tables at all.

So, wouldn't it be a better solution to use the `--single-transaction` parameter instead?

Kind regards

### PR DESCRIPTION
**Pull request by Tronde**
Hi,
this PR close nextcloud/documentation#375. Will it be backported to the branches stable11, stable10 and stable9 by some automatism or should I create PRs for these branches as well?

Best regards,
Tronde

### CODE REVIEW

**Comment by tflidd** [comment]
Tested and works for me.
:+1:

**Comment by Tronde** [comment]
Hello,
Because this is my first time I contribute to the Nextcloud Documentation I'm not sure if I'm allowed to merge this pull request.

The change was approved, all checks have passed, the branch has no conflicts with the base branch and I see a green button "Merge pull request". Am I allowed to merge this PR or is it a task for another guy?

I don't want to get into any trouble so I ask.

Regards,
Tronde

**Comment by tflidd** [comment]
For most PRs, it is a different person that finally merges the changes.

You could already prepare the backports. Not sure what the most efficient way is, I did it with cherry-picking on the other branch. There could be much better ways @nickvergessen

**Comment by nickvergessen** [comment]
Nope, exactly like that

**Comment by tflidd** [comment]
backport for NC 11: https://github.com/nextcloud/documentation/pull/416

**Comment by MorrisJobke** [comment]
@Tronde For the documentation repo it's okay to merge it once you got a positive review :)

**Pull request merged**
