### PR TITLE
fix: explictly add sphinx_rtd_theme to extensions to fix search

### LINKED ISSUE #9905: Search doesn't work due to missing jQuery
1) Open https://docs.nextcloud.com/server/latest/developer_manual/search.html?q=kaboom

Bildschirmfoto vom 2023-03-16 12-24-47

### PR DESCRIPTION
**Pull request by st3iny**
Fix #9905

Ref https://sphinx-rtd-theme.readthedocs.io/en/stable/changelog.html#known-issues

### CODE REVIEW

**Review by st3iny — COMMENTED** [review]
I tested it locally and the search works again. Note that sphinx v6 has to be manually installed to be able to reproduce the issue.

`pip install sphinx==6`

**Review by ChristophWurst — APPROVED** [review]

**Comment by nickvergessen** [comment]
And backport to stable24 I guess?

**Comment by nickvergessen** [comment]
23 seems also broken:
https://docs.nextcloud.com/server/23/user_manual/en/search.html

Can we backport all the thigns there too?

**Comment by st3iny** [comment]
> 23 seems also broken: https://docs.nextcloud.com/server/23/user_manual/en/search.html
> 
> Can we backport all the thigns there too?

Done (#9942)

**Pull request merged**
