### PR TITLE
Document unified search API

### PR DESCRIPTION
**Pull request by ChristophWurst**
- [x] Blocked by the API changes from https://github.com/nextcloud/server/pull/20916
- [x] Requires https://github.com/nextcloud/documentation/pull/2164

### CODE REVIEW

**Comment by kesselb** [comment]
cc @marcelklehr @raimund-schluessler does that make sense to you? ;)

**Comment by kesselb** [comment]
Also @korelstar for notes ;)

**Comment by marcelklehr** [comment]
LGTM.

Currently, a lot of apps override the default search bar in the menu bar to hook in to their custom search functionality. How do we deal with that? Is that functionality expected to be removed in favor of this new search API?

**Comment by ChristophWurst** [comment]
> Currently, a lot of apps override the default search bar in the menu bar to hook in to their custom search functionality. How do we deal with that? Is that functionality expected to be removed in favor of this new search API?

Most likely, yeah. But the UI part is still to do, so there's a lot that might change. :eyes: @skjnldsv @jancborchardt 

Ref https://github.com/orgs/nextcloud/projects/38

**Comment by jancborchardt** [comment]
> Currently, a lot of apps override the default search bar in the menu bar to hook in to their custom search functionality. How do we deal with that? Is that functionality expected to be removed in favor of this new search API?

Yes, so the idea is that the search bar in the header will become the unified search and work the same anywhere.

In-app search would then move into each app, ideally to the top of the AppNavigation to filter content as-you-type. A great example there is Talk, and the same would be possible design-wise for Files, Mail, Contacts, Activity, Bookmarks, Notes, etc. :)

**Pull request merged**
