### PR TITLE
Update deprecated globals in 18

### PR DESCRIPTION
**Pull request by ChristophWurst**
Ref https://github.com/nextcloud/server/pull/17402
Ref https://github.com/nextcloud/server/pull/17392

### CODE REVIEW

**Comment by korelstar** [comment]
This should be added to https://github.com/nextcloud/eslint-plugin/blob/master/lib/rules/no-deprecations.js , too.

**Comment by ChristophWurst** [comment]
Will do today :)

**Comment by ChristophWurst** [comment]
The file is not in stable18 :shrug:

**Pull request merged**
