### PR TITLE
Add php APCu hint to command line based updater

### PR DESCRIPTION
**Pull request by R0Wi**
With respect to https://github.com/nextcloud/server/issues/27781 we should add a hint regarding the PHP CLI parameters for APCu like we did in  https://github.com/nextcloud/documentation/commit/c5fa1b6859edfc20477719cf77488a797719e7c3#diff-48dc187eeb03371b5ad6886b33043bf060884809c1d51a3568c5d29e40e3bf13 and https://github.com/nextcloud/documentation/commit/38a0a33e4edc3b7bc18f05ecf190eaf010dea1f4#diff-48dc187eeb03371b5ad6886b33043bf060884809c1d51a3568c5d29e40e3bf13 for the cronjob.

### CODE REVIEW

**Review by kesselb — APPROVED** [review]

**Comment by TP75** [comment]
Always good to see the newbies showing the oldies how to kindly improve the docs and how to support the community, I presume. Thanks @R0Wi  a lot.

**Comment by R0Wi** [comment]
@TP75 do you think this hint would also make sense on the background jobs page https://github.com/nextcloud/documentation/blob/e62af941d49e509259ae906f2e667de669c108e4/admin_manual/configuration_server/background_jobs_configuration.rst ?

**Comment by R0Wi** [comment]
> @TP75 do you think this hint would also make sense on the background jobs page https://github.com/nextcloud/documentation/blob/e62af941d49e509259ae906f2e667de669c108e4/admin_manual/configuration_server/background_jobs_configuration.rst ?

**Update**: i think this was already done in https://github.com/nextcloud/documentation/commit/c0d2eaeb1b57079f9c019351cca10f51be408b11 and https://github.com/nextcloud/documentation/commit/65e9afeaa181426eefd8ee0df314431b4cde9a42 :+1:

**Pull request merged**
