### PR TITLE
Update big_file_upload_configuration.rst

### PR DESCRIPTION
**Pull request by bobbylansing1**
Link previously ends at 404. I believe this is the correct location for the link (Client Configuration options).

Signed-off-by: bobbylansing1 <116922104+bobbylansing1@users.noreply.github.com>

### CODE REVIEW

**Review by tflidd — CHANGES_REQUESTED** [review]
But you don't link to the same corresponding page in the manual. For the current version it would be:
https://docs.nextcloud.com/desktop/latest/advancedusage.html

**Comment by ChristophWurst** [comment]
So. Finish or close? ;)

**Comment by joshtrichards** [comment]
https://github.com/nextcloud/documentation/pull/9265#pullrequestreview-1447353180

**Comment by ChristophWurst** [comment]
I'm asking because the one line change is not correct and there hasn't been any update for months.

We may just close the PR.

**Comment by kesselb** [comment]
We thank you for your contribution :+1: 

I am closing the pull request because there has been no activity for a while now.

**Pull request closed without merging**
