### PR TITLE
Update middlewares.rst

### PR DESCRIPTION
**Pull request by fsamapoor**
The plural of middleware is middleware.

https://english.stackexchange.com/questions/257120/middleware-vs-middlewares

### CODE REVIEW

**Comment by fsamapoor** [comment]
Hello @ChristophWurst,

Do I need to wait for someone else to merge my own PRs with an "approved review" in this particular repository?

Some of them take days to get merged in and it seems to me it is safe to merge minor changes myself, once it has at least an approved review.

**Comment by ChristophWurst** [comment]
After approval and green CI it's generally ok to merge

**Comment by fsamapoor** [comment]
> After approval and green CI it's generally ok to merge

Thanks.
I also noticed there are some backporting strategies in place that I'm not quite familiar with at the moment.
Better safe than sorry :)

**Comment by ChristophWurst** [comment]
We try to get fixes backported to all major versions still supported. See https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule for an overview.

https://docs.nextcloud.com/server/latest/developer_manual/getting_started/development_process.html#bugfixes

**Comment by fsamapoor** [comment]
Thank you. Will try with this PR to see if I'm able to follow the lead.

**Pull request merged**
