### PR TITLE
enh(Maintenance): update sync with clients after data recovery

### PR DESCRIPTION
**Pull request by kyteinsky**
All other steps are already good.

### 🖼️ Screenshots

image

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Nice

**Comment by ChristophWurst** [comment]
nit: `enh` is not a typical conventional commit by most conventions. Use `feat`

**Comment by kyteinsky** [comment]
> nit: `enh` is not a typical conventional commit by most conventions. Use `feat`

cool

**Pull request merged**
