### PR TITLE
fix(dev): Adjust Exception explanations in OpenAPI tutorial

### PR DESCRIPTION
**Pull request by provokateurin**
### ☑️ Resolves

* Fix https://github.com/nextcloud/documentation/issues/11915

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Comment by come-nc** [comment]
I still wonder what bad it would do to have the middleware turn all uncatched throwables into json.

**Comment by provokateurin** [comment]
It would certainly make it better, but it's technically a breaking change.

**Pull request merged**
