### PR TITLE
Do not (yet) recommended PHP 7.4

### PR DESCRIPTION
**Pull request by J0WI**
https://github.com/nextcloud/3rdparty/pull/435#issuecomment-622107360
https://github.com/nextcloud/3rdparty/pull/432#issuecomment-615914859
https://github.com/nextcloud/server/issues/18996

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Most of this seem to be fixed in https://github.com/nextcloud/server/pull/20794

**Comment by J0WI** [comment]
Let's see if we still need it on 18-stable or if it gets backported.

**Comment by tflidd** [comment]
What is the status here? The new release comes out soon, so people will come check for updates/upgrades and work on their systems.

**Comment by ChristophWurst** [comment]
> Most of this seem to be fixed in [nextcloud/server#20794](https://github.com/nextcloud/server/pull/20794)

@tflidd doesn't that fix the issues?

**Comment by J0WI** [comment]
Superseded by #2117

**Comment by abysso2** [comment]
Just installed 18.0.5 ...

root@nextcloud:~# grep VER /var/www/nextcloud/3rdparty/leafo/scssphp/src/Version.php
const VERSION = 'v0.7.6';

So there ist no update to 0.8.4 as mentioned here: nextcloud/3rdparty#361

Is the php7.4-error still existant????

**Comment by J0WI** [comment]
Yes, as you can read in the comments above the fix is only in Nextcloud 19 and has not been backported to 18.

**Comment by kesselb** [comment]
Actually there are no stupid questions but @abysso2 comment is very close 😉

**Pull request closed without merging**
