### PR TITLE
docs(admin): Emphasize recommended versions in db chapter

### PR DESCRIPTION
**Pull request by joshtrichards**
### ☑️ Resolves

More strongly emphasize that picking the *version* of your preferred database is also important. 

- Mention it
- Link to system requirements
- Add a note call-out
- Clarify the steps for db deployment as bullet points for the reader

Context: Some people merely use the `latest` tags their MariaDB Docker stacks or install the latest from vendor repositories without paying attention to the versions recommended by us. Not surprisingly they run into problems from time to time (like the latest breaking changes that were in MariaDB 11.3.x images -- which we don't even support since it's a short-term release). 

Every little nudge in the right direction helps.

Side note: Anyone know why the Database config section isn't just a chapter under *Installation and server configuration*? It's kind of weird that it's arbitrarily near the end of the Admin Manual, since it's a prerequisite to any deployment.

### 🖼️ Screenshots

image

### CODE REVIEW

**Review by kesselb — APPROVED** [review]
Good recommendation, Thank you :pray:

**Comment by zmweske** [comment]
should the mariadb version include v10.6? That is what is listed under https://github.com/nextcloud/docker?tab=readme-ov-file#running-this-image-with-docker-compose

**Comment by nickvergessen** [comment]
DB versions are listed in https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html

**Comment by zmweske** [comment]
Ok, it looks like it was updated since posting the comment: 
(image)
Just wanted to make sure that things were consistent

**Comment by zmweske** [comment]
Looks like it is more updated now: 
image

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/documentation/commit/97910350748d872062dda41e728a098599d63963 2 months ago, but all good

**Comment by zmweske** [comment]
Oh it looks like they are both listed as latest, even though one is definitely not. I'll post the links when I get back to my comp

**Comment by zmweske** [comment]
Yeah, the problem was that both the page title and the menu in the bottom right said latest when it was not: https://docs.nextcloud.com/server/21/admin_manual/installation/system_requirements.html (obv v21 when looking through the url)

**Comment by joshtrichards** [comment]
@zmweske Indeed. Been attempting to fix that (e.g. #11628), but it's a work in progress still. :)

**Comment by zmweske** [comment]
No worries, been there hahaha

**Pull request merged**
