### PR TITLE
Add basic docs for Trash and Versions webdav API

### PR DESCRIPTION
**Pull request by rullzer**
Has to be backported to 14 when merged

@tobiasKaminsky @icewind1991 since you worked with the API's already please have a look

CC: @marinofaggiana

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
I saw on other docs (if I remember correctly on E2E) that there were also sample cURL calls and sample responses.
I think this is very convenient for any other dev.
(maybe it is good to have something like an API template, so that this has only to be adjusted…)
If you need help, ping me :-)

**Comment by MorrisJobke** [comment]
stable14 7fa4216d

**Comment by marinofaggiana** [comment]
Hi, is not clear the restoring from the trashbin : 

https://cloud.example.com/remote.php/dav/trashbin/USER/restore
This will automatically restore the item to its original location.

how I pass the parameter for the item ?

**Comment by rullzer** [comment]
@marinofaggiana as it says you need to move the item from the trash to the restore

**Comment by marinofaggiana** [comment]
@rullzer it's possible have a thumbnail of image in /trashbin/user/.... with API /index.php/apps/files/api/v1/thumbnail/ or /index.php/core/preview.png ? 

I have make a few test but return always 404

**Comment by tobiasKaminsky** [comment]
You have to use
/index.php/apps/files_trashbin/preview?fileId=123123&x=128&&y=128

fileId: id on server instance, without serverId
x, y: height/width in px

**Comment by marinofaggiana** [comment]
@tobiasKaminsky not works ... are you sure ?

ex. https://cloud.nextcloud.com/index.php/apps/files_trashbin/preview?fileId=795978&x=128&y=128

please verify :-)

**Comment by marinofaggiana** [comment]
Issue with restore : I move 5 file with different task (at the same time, not serialized) from trash to /restore/ but for a few file return error 500 ... the strange is that the all file are  correctly  restored.

Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: internal server error (500)" UserInfo={NSLocalizedDescription=Request failed: internal server error (500), NSErrorFailingURLKey=https://cloud.nextcloud.com/remote.php/dav/trashbin/marinofaggiana/trash/11-03-13%2001-17-25%200001.jpg.d1539776765, com.alamofire.serialization.response.error.data=

**Comment by MorrisJobke** [comment]
> Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: internal server error (500)" UserInfo={NSLocalizedDescription=Request failed: internal server error (500), NSErrorFailingURLKey=https://cloud.nextcloud.com/remote.php/dav/trashbin/marinofaggiana/trash/11-03-13%2001-17-25%200001.jpg.d1539776765, com.alamofire.serialization.response.error.data=

Check the nextcloud server log for more details please. Internal server error always leaves log entries.

**Comment by marinofaggiana** [comment]
@MorrisJobke I use https://cloud.nextcloud.com/ ... I can't view the server log

**Comment by marinofaggiana** [comment]
the issue also occurs with delete.

**Comment by marinofaggiana** [comment]
ping, please, who can look here ?

**Comment by tobiasKaminsky** [comment]
I also do not have access to the logs, but you can always setup your own server.
This has two advantages
- we can rule out an error on c.nc.c
- you have full access to the complete server and can apply a patch, if neeeded
- (developing on a productive server feels in my opinion always a bit risky to loose some data)

**Comment by marinofaggiana** [comment]
@tobiasKaminsky I have an old 13 ... next week step to 14 but not

**Comment by MorrisJobke** [comment]
```json
{
    "reqId": "FPJz45cMvWNtOGztPonU",
    "level": 4,
    "time": "2018-10-17T11:46:11+00:00",
    "remoteAddr": "213.x.x.x",
    "user": "marinofaggiana",
    "app": "webdav",
    "method": "MOVE",
    "url": "/remote.php/dav/trashbin/marinofaggiana/trash/11-03-13%2001-17-25%200001.jpg.d1539776765",
    "message": {
        "Exception": "OCP\\Lock\\LockedException",
        "Message": "\"files/d68e4782d0734361c1e325ac7945a865\" is locked, existing lock on file: none",
        "Code": 0,
        "Trace": [
            {
                "file": "/var/www/html/lib/private/Files/Storage/Common.php",
                "line": 713,
                "function": "acquireLock",
                "class": "OC\\Lock\\MemcacheLockingProvider",
                "type": "->",
                "args": [
                    "files/d68e4782d0734361c1e325ac7945a865",
                    2
                ]
            },
            {
                "file": "/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php",
                "line": 592,
                "function": "acquireLock",
                "class": "OC\\Files\\Storage\\Common",
                "type": "->",
                "args": [
                    "scanner::files_trashbin/versions",
                    2,
                    {
                        "__class__": "OC\\Lock\\MemcacheLockingProvider"
                    }
                ]
            },
            {
                "file": "/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php",
                "line": 592,
                "function": "acquireLock",
                "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
                "type": "->",
                "args": [
                    "scanner::files_trashbin/versions",
                    2,
                    {
                        "__class__": "OC\\Lock\\MemcacheLockingProvider"
                    }
                ]
            },
            {
                "file": "/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php",
                "line": 592,
                "function": "acquireLock",
                "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
                "type": "->",
                "args": [
                    "scanner::files_trashbin/versions",
                    2,
                    {
                        "__class__": "OC\\Lock\\MemcacheLockingProvider"
                    }
                ]
            },
            {
                "file": "/var/www/html/lib/private/Files/Cache/Scanner.php",
                "line": 331,
                "function": "acquireLock",
                "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
                "type": "->",
                "args": [
                    "scanner::files_trashbin/versions",
                    2,
                    {
                        "__class__": "OC\\Lock\\MemcacheLockingProvider"
                    }
                ]
            },
            {
                "file": "/var/www/html/apps/files_trashbin/lib/Trashbin.php",
                "line": 864,
                "function": "scan",
                "class": "OC\\Files\\Cache\\Scanner",
                "type": "->",
                "args": [
                    "files_trashbin/versions"
                ]
            },
            {
                "file": "/var/www/html/apps/files_trashbin/lib/Trashbin.php",
                "line": 476,
                "function": "getVersionsFromTrash",
                "class": "OCA\\Files_Trashbin\\Trashbin",
                "type": "::",
                "args": [
                    "11-03-13 01-17-25 0001.jpg",
                    1539776765,
                    "marinofaggiana"
                ]
            },
            {
                "file": "/var/www/html/apps/files_trashbin/lib/Trashbin.php",
                "line": 428,
                "function": "restoreVersions",
                "class": "OCA\\Files_Trashbin\\Trashbin",
                "type": "::",
                "args": [
                    {
                        "__class__": "OC\\Files\\View"
                    },
                    "11-03-13 01-17-25 0001.jpg.d1539776765",
                    "11-03-13 01-17-25 0001.jpg",
                    "11-03-13 01-17-25 0001.jpg",
                    "Photos",
                    1539776765
                ]
            },
            {
                "file": "/var/www/html/apps/files_trashbin/lib/Sabre/TrashFile.php",
                "line": 79,
                "function": "restore",
                "class": "OCA\\Files_Trashbin\\Trashbin",
                "type": "::",
                "args": [
                    "11-03-13 01-17-25 0001.jpg.d1539776765",
                    "11-03-13 01-17-25 0001.jpg",
                    1539776765
                ]
            },
            {
                "file": "/var/www/html/apps/files_trashbin/lib/Sabre/RestoreFolder.php",
                "line": 83,
                "function": "restore",
                "class": "OCA\\Files_Trashbin\\Sabre\\TrashFile",
                "type": "->",
                "args": []
            },
            {
                "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php",
                "line": 158,
                "function": "moveInto",
                "class": "OCA\\Files_Trashbin\\Sabre\\RestoreFolder",
                "type": "->",
                "args": [
                    "11-03-13 01-17-25 0001.jpg.d1539776765",
                    "trashbin/marinofaggiana/trash/11-03-13 01-17-25 0001.jpg.d1539776765",
                    {
                        "__class__": "OCA\\Files_Trashbin\\Sabre\\TrashFile"
                    }
                ]
            },
            {
                "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
                "line": 646,
                "function": "move",
                "class": "Sabre\\DAV\\Tree",
                "type": "->",
                "args": [
                    "trashbin/marinofaggiana/trash/11-03-13 01-17-25 0001.jpg.d1539776765",
                    "trashbin/marinofaggiana/restore/11-03-13 01-17-25 0001.jpg.d1539776765"
                ]
            },
            {
                "function": "httpMove",
                "class": "Sabre\\DAV\\CorePlugin",
                "type": "->",
                "args": [
                    {
                        "absoluteUrl": "https://cloud.nextcloud.com/remote.php/dav/trashbin/marinofaggiana/trash/11-03-13%2001-17-25%200001.jpg.d1539776765",
                        "__class__": "Sabre\\HTTP\\Request"
                    },
                    {
                        "__class__": "Sabre\\HTTP\\Response"
                    }
                ]
            },
            {
                "file": "/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php",
                "line": 105,
                "function": "call_user_func_array",
                "args": [
                    [
                        {
                            "__class__": "Sabre\\DAV\\CorePlugin"
                        },
                        "httpMove"
                    ],
                    [
                        {
                            "absoluteUrl": "https://cloud.nextcloud.com/remote.php/dav/trashbin/marinofaggiana/trash/11-03-13%2001-17-25%200001.jpg.d1539776765",
                            "__class__": "Sabre\\HTTP\\Request"
                        },
                        {
                            "__class__": "Sabre\\HTTP\\Response"
                        }
                    ]
                ]
            },
            {
                "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
                "line": 479,
                "function": "emit",
                "class": "Sabre\\Event\\EventEmitter",
                "type": "->",
                "args": [
                    "method:MOVE",
                    [
                        {
                            "absoluteUrl": "https://cloud.nextcloud.com/remote.php/dav/trashbin/marinofaggiana/trash/11-03-13%2001-17-25%200001.jpg.d1539776765",
                            "__class__": "Sabre\\HTTP\\Request"
                        },
                        {
                            "__class__": "Sabre\\HTTP\\Response"
                        }
                    ]
                ]
            },
            {
                "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
                "line": 254,
                "function": "invokeMethod",
                "class": "Sabre\\DAV\\Server",
                "type": "->",
                "args": [
                    {
                        "absoluteUrl": "https://cloud.nextcloud.com/remote.php/dav/trashbin/marinofaggiana/trash/11-03-13%2001-17-25%200001.jpg.d1539776765",
                        "__class__": "Sabre\\HTTP\\Request"
                    },
                    {
                        "__class__": "Sabre\\HTTP\\Response"
                    }
                ]
            },
            {
                "file": "/var/www/html/apps/dav/lib/Server.php",
                "line": 293,
                "function": "exec",
                "class": "Sabre\\DAV\\Server",
                "type": "->",
                "args": []
            },
            {
                "file": "/var/www/html/apps/dav/appinfo/v2/remote.php",
                "line": 35,
                "function": "exec",
                "class": "OCA\\DAV\\Server",
                "type": "->",
                "args": []
            },
            {
                "file": "/var/www/html/remote.php",
                "line": 163,
                "args": [
                    "/var/www/html/apps/dav/appinfo/v2/remote.php"
                ],
                "function": "require_once"
            }
        ],
        "File": "/var/www/html/lib/private/Lock/MemcacheLockingProvider.php",
        "Line": 80,
        "CustomMessage": "--"
    },
    "userAgent": "Mozilla/5.0 (iOS) Nextcloud-iOS/2.22.5",
    "version": "14.0.3.0"
}
```

**Comment by marinofaggiana** [comment]
@MorrisJobke who has write this API ? @icewind1991 ?

**Comment by marinofaggiana** [comment]
@rullzer do you have a bit time for this issue ? for me it's important for function as delete ALL record or restore ALL record

**Comment by rullzer** [comment]
I can add it to the todo list. But not right now.

Just in general. A restore all would potentially move gigabytes of data. So that is almost asking for trouble.

**Comment by marinofaggiana** [comment]
> I can add it to the todo list. But not right now.

ok, thx

> Just in general. A restore all would potentially move gigabytes of data. So that is almost asking for trouble.

as move on Files view ... but the issue is  also for "delete" ...

**Comment by rullzer** [comment]
@marinofaggiana could you in the future report such issues to the server repo as it is not really a documentation issue :wink: 

Also. Maybe for now remove the restore all button then. As I can't give an ETA when it will be fixed.

**Comment by marinofaggiana** [comment]
@rullzer absolutely yes ! thanks

**Comment by marinofaggiana** [comment]
@rullzer absolutely yes ! thanks

**Comment by marinofaggiana** [comment]
@rullzer absolutely yes ! thanks

**Comment by marinofaggiana** [comment]
@rullzer absolutely yes ! thanks

**Pull request merged**
