### PR TITLE
add description of new OCS endpoint

### PR DESCRIPTION
**Pull request by sualko**
for recommendations of files and folders

see nextcloud/recommendations#458

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Should we document what happens when the app is disabled?

**Comment by sualko** [comment]
For me that's beyond the description of this single endpoint and related more general to the way Nextcloud handles ocs. Not sure if that has been documentated somewhere already. If you like I can put it somewhere or also on the new page. A hint hurts no one :-)

**Comment by ChristophWurst** [comment]
Fair enough. Let's just add a note/warning that the app isn't always enabled

**Comment by sualko** [comment]
I added a notice that the recommendations app needs to be enabled.

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
