### PR TITLE
Documentation for enabling changing passwords in user_ldap

### PR DESCRIPTION
**Pull request by GitHubUser4234**
This is the documentation for [#1715](https://github.com/nextcloud/server/pull/1715).  @blizzz :)

### CODE REVIEW

**Comment by GitHubUser4234** [comment]
@blizzz related screenshot has been updated, too. However after trying Firefox on CentOS and Windows, it was somehow still not possible to completely match the layout of the previous one.

**Comment by blizzz** [comment]
@GitHubUser4234 thank you, I'll give it a look tomorrow!

**Comment by GitHubUser4234** [comment]
@blizzz thanks for the review, I tried to implement the change.

**Comment by blizzz** [comment]
@GitHubUser4234 thank you, 👍 

@MorrisJobke mind having a look?

**Comment by GitHubUser4234** [comment]
Yippie :D

**Pull request merged**
