### PR TITLE
Use IPv6 too in the Nginx config

### PR DESCRIPTION
**Pull request by C0rn3j**
Added IPv6 listens. Without them Nextcloud won't work over IPv6.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @josh4trunks

**Comment by josh4trunks** [comment]
I do not personally use IPv6. Do you really need both `listen 80;` and `listen [::]:80;`?
Can you not just put `listen [::]:80;` if you want to listen on both IPv4 and IPv6?

**Comment by C0rn3j** [comment]
There's a **Linux only**(might have changed since I last checked) flag you can set which would result having in having a single IPv6 line. 

I think the way I initially suggested is more clear and cross platform.

listen [::]:443 ssl http2 ipv6only=off;

**Comment by josh4trunks** [comment]
Ok, I agree the way you suggest is best.
👍

**Comment by MorrisJobke** [comment]
stable12 f62ee839

**Pull request merged**
