### PR TITLE
including android user manual

### PR DESCRIPTION
**Pull request by odev954**
Fixed some issues in the user manual:
* allocating the user manual from the android repository to the documentation repository (see the reference: https://github.com/nextcloud/documentation/issues/978)
* fixed the issue in the `android_app.rst` file (see the reference: https://github.com/nextcloud/documentation/issues/1856)

Note: if the image size is still unmatched the size of the screen, you can adjust it in the figure properties:
```rst
.. figure:: images/android-4.png
   :scale: 50 % <-- CHANGE THE VALUE HERE
   :alt: Your Nextcloud Files page.
```

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@tobiasKaminsky Is this planned like that?

cc @rullzer @skjnldsv

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky Is this planned like that?

Yeah, let us have it here, same should maybe done for desktop doc, or?

**Comment by MorrisJobke** [comment]
> Yeah, let us have it here, same should maybe done for desktop doc, or?

I'm still unsure, because this here is based on the server release schedule (18, 19, 20, ...) and also expires like that. So maintaining Android schedule and desktop schedule ontop of this sounds not like the best plan to do.

**Comment by MorrisJobke** [comment]
After some chat with @tobiasKaminsky we think that this manual should not be needed. The app should be as self explanatory as possible.

Also maintaining the manual in here makes very little sense for a one page manual that explains the obvious steps the app already guides you through. Beside that the server documentation is maintained based on the releases of the server and thus keeping them in sync with the android manual makes the whole thing just more complex.

I really appreciate your help. Sorry that we will reject this for now.

**Comment by odev954** [comment]
It's okay, I just wanted to see how pull requests work :) (I'm pretty new to GitHub)
Anyway, I set up the nextCloud server on my VM lately and I ready to get started with some of the issues in the android application. I'm hoping that I will find the time to contribute more to the nextCloud project in the future.
Thank you anyway! ;)

**Pull request closed without merging**
