### PR TITLE
Fix .drone.yml syntax

### PR DESCRIPTION
**Pull request by MorrisJobke**

### CODE REVIEW

**Comment by skjnldsv** [comment]
This is the same as #1360? :thinking:

**Comment by MorrisJobke** [comment]
> This is the same as #1360? 🤔

Yes - this is this. 🤪

**Comment by MorrisJobke** [comment]
Ah - you meant #1356 - let's see if this works now and then would merge this otherwise look into your PR.

**Comment by skjnldsv** [comment]
Ah yes, sorry! Wrong autocompletion by github :p

**Pull request merged**
