### PR TITLE
Update example_centos.rst

### PR DESCRIPTION
**Pull request by bkmgit**
Update reference location for listing of PHP modules

### CODE REVIEW

**Comment by bkmgit** [comment]
Sorry, looks like will need to redo this, deleted the repository upon merging of first pull request.

**Comment by skjnldsv** [comment]
> Sorry, looks like will need to redo this, deleted the repository upon merging of first pull request.

What is the issue? :)

**Comment by bkmgit** [comment]
@skjnldsv Are you able to get this commit merged or should I make it again? I certify I made the changes and can submit them to the project.

**Comment by bkmgit** [comment]
DCO check does not pass.

**Comment by bkmgit** [comment]
Signed-off-by: Benson Muite <benson_muite@emailplus.org>

**Comment by skjnldsv** [comment]
> DCO check does not pass.

yeah you need to sign your commits, but that's ok, it's not a crazy big change :)

**Pull request merged**
