### PR TITLE
Fix indefinite article before Nextcloud (an->a)

### PR DESCRIPTION
**Pull request by uusijani**

### CODE REVIEW

**Comment by uusijani** [comment]
@juliushaertl Is backporting for docs also done [as per the manual](https://docs.nextcloud.com/server/stable/developer_manual/general/backporting.html)? It seems pretty straightforward, so I think I can produce those pull requests too, if needed.

**Comment by skjnldsv** [comment]
@uusijani not for the documentation.
And I think the backporting docs should also be updated. Thought @MorrisJobke @rullzer ?
We do not mention Frank every time now, do we?

**Comment by MorrisJobke** [comment]
We need to update the docs about our new bot and also that @rullzer and me now decide about the backports

**Pull request merged**
