### PR TITLE
Add PostgreSQL version 12 and 13 to requirements

### LINKED ISSUE #5321: Update NC requirements regarding Postgres databases
As stated in this thread https://help.nextcloud.com/t/postgres-13-support/93184, Postgres 13 seems to work fine with both NC 19 and NC 20.

I propose to update the following doc page for the two versions to reflect this: https://docs.nextcloud.com/server/20/admin_manual/installation/system_requirements.html

### PR DESCRIPTION
**Pull request by Chartman123**
Fixes #5321 

Signed-off-by: Christian Hartmann <chris-hartmann@gmx.de>

### CODE REVIEW

**Comment by Chartman123** [comment]
Fixes #5321

**Comment by Chartman123** [comment]
I think that this could get backported to Stable 20, too.

**Review by tflidd — APPROVED** [review]

**Comment by Chartman123** [comment]
@MorrisJobke is there anything missing for getting this merged?

**Comment by MorrisJobke** [comment]
> @MorrisJobke is there anything missing for getting this merged?

Not really :)

**Comment by jakubgs** [comment]
The website still shows 11 as newest supported version:

image

**Comment by Chartman123** [comment]
@jakubgs The docs for 21 and 22 show the correct versions 👍🏻  Which version did you check?

**Comment by jakubgs** [comment]
Hm, now it looks correct:

image

Maybe I indeed was looking at an older version.

**Pull request merged**
