### PR TITLE
Remove Nginx section about compiling a module and combine the two Nginx pages into one

### PR DESCRIPTION
**Pull request by MorrisJobke**
I put the performance tuning section directly into the recommended Nginx section and removed the part about self compiling a Nginx module and outdated configuration for the old gallery apps.

cc @josh4trunks just to be sure, but I use the `http2` option in my environments as well.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
BTW: My big plan is to combine the two Nginx config pages into one 😉

**Comment by MorrisJobke** [comment]
> BTW: My big plan is to combine the two Nginx config pages into one 😉

Okay. I just did it in here.

**Comment by benediktg** [comment]
> I use the http2 option in my environments as well.

I'm also using http2 and have no problems. 😉

**Comment by josh4trunks** [comment]
Awesome, less to maintain!

**Comment by josh4trunks** [comment]
@MorrisJobke Unrelated to this specific issue but I was looking to a the necessity of the block starting with...
`location ~* \.(?:png|html|ttf|ico|jpg|jpeg)$ {`

In my testing Nextcloud does not actually serve any of these files directly except for **html** and a single/few **png**s
The following seemed to work fine on my Nextcloud v11.0.3
`location ~* \.(?:html|png)$ {`

**Comment by josh4trunks** [comment]
Also for `location ~* \.(?:css|js|woff|svg|gif)$ {`, is there any reason we can not set `max-age=15778463` like the .htaccess does?

**Comment by MorrisJobke** [comment]
Looks like you are right, could you send a PR?

**Comment by josh4trunks** [comment]
See my PR here https://github.com/nextcloud/documentation/pull/466.

**Pull request merged**
