### PR TITLE
chore(pip): Clean up version management

### PR DESCRIPTION
**Pull request by ChristophWurst**
* Pipfile.lock added
* `pip freeze > requirements.txt` to lock installed versions and keep Pipfile as the source of truth
* Add `sphinxcontrib-phpdomain` to Pipfile

> Pipfiles contain information for the dependencies of the project, and supersedes the requirements.txt file used in most Python projects.

https://pipenv-fork.readthedocs.io/en/latest/basics.html#example-pipfile-pipfile-lock

Beware I'm not a Python developer.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> If you have any Python dependencies that your project needs (themes, build tools, etc) then place them in a requirements.txt file inside your docs folder.

https://github.com/ammaraskar/sphinx-action

:smiling_face_with_tear: :smiling_face_with_tear: :smiling_face_with_tear:

**Comment by ChristophWurst** [comment]
Someone enlighten me but why do we need Pipfile and requirements.txt? And can we drop one of the two?

**Comment by ChristophWurst** [comment]
I give up.

**Comment by st3iny** [comment]
Pipenv can create a locked requirements.txt via `pipenv requirements`. I recommend ditching requirements.txt entirely to have a single source of truth. Otherwise, we would need a CI job to check if both files are in sync. That would require adjusting our deploy process, though.

**Comment by ChristophWurst** [comment]
> I recommend ditching requirements.txt entirely to have a single source of truth.

https://github.com/nextcloud/documentation/pull/9550#issuecomment-1380470429

well

**Comment by st3iny** [comment]
> > If you have any Python dependencies that your project needs (themes, build tools, etc) then place them in a requirements.txt file inside your docs folder.
> 
> https://github.com/ammaraskar/sphinx-action
> 
> smiling_face_with_tear smiling_face_with_tear smiling_face_with_tear

Haha, I just failed on the same point. 

Python is nice and all but reproducible builds are just impossible and it surely is not portable.

**Comment by christianlupus** [comment]
May I ask: Why both pipfile and requirements.txt? Dependabot allows working with requirements.txt as far as I understand the docs. The alternative would be to drop the requirements.txt file.

**Comment by st3iny** [comment]
> May I ask: Why both pipfile and requirements.txt? Dependabot allows working with requirements.txt as far as I understand the docs. The alternative would be to drop the requirements.txt file.

Yeah, we both tried to drop requirements.txt. The GitHub action sphinxbuild is not compatible with pipenv. Maybe we should drop Pipfile and switch to requirements.txt instead.

**Comment by christianlupus** [comment]
> Pipenv can create a locked requirements.txt via `pipenv requirements`. I recommend ditching requirements.txt entirely to have a single source of truth. Otherwise, we would need a CI job to check if both files are in sync. That would require adjusting our deploy process, though.

Is the deployment process here on GitHub in the actions or also on some other infrastructure?

The alternative is to make the GitHub action compatible with Pipfile. Maybe they would accept gratefully a PR?

I might be able to help but would need your preference on what to do...

**Comment by ChristophWurst** [comment]
> The alternative is to make the GitHub action compatible with Pipfile. Maybe they would accept gratefully a PR?

Open a ticket and we an see if they would accept that change.

**Comment by christianlupus** [comment]
I read a bit in the issues of the action. They seem not to be too forthcoming as python supports multiple dependency management systems.

I instead tried a bit with the documentation and was left with [this approach](https://github.com/christianlupus-nextcloud/documentation/tree/dev/pipenv). I removed the `requirements.txt` and created it on the fly from the `Pipenv.lock` file. Would that be as you see fit here? If yes, I can rebase, fix the commit messages and open a PR against the upstream repo.

**Comment by christianlupus** [comment]
Any comments by you, @ChristophWurst or @st3iny?

**Comment by ChristophWurst** [comment]
I am not opposed that solution. One of the two files has to go. I don't have a preference if we should stay with requirements.txt or Pipfile.lock.

https://github.com/nextcloud/documentation/pull/9551#issuecomment-1380619775 @st3iny found some arguments for requirements.txt over Pipenv.lock

**Pull request closed without merging**
