### PR TITLE
revise updater.server.url to reflect nextcloud.org URL

### PR DESCRIPTION
**Pull request by hailthemelody**
Please see https://github.com/nextcloud/server/issues/102 for further information.

(meta: including from conversation in above url @LukasReschke )

### CODE REVIEW

**Comment by mar1u5** [comment]
THX. Could you prepare an backport to the `stable9` branch? 💪

**Comment by hailthemelody** [comment]
I would be happy to but I haven't prepared a backport before. Would you mind pointing me in the right direction?

**Comment by mar1u5** [comment]
It is as easy as you open another PR with the same commit ... but you select `stable9` as the branch you want to commit to instead of `master` 😉 ...if you have problems - i can do this for you 💪

**Comment by hailthemelody** [comment]
Donezo - looks good?

**Comment by MorrisJobke** [comment]
> Donezo - looks good?

Apply the changes ontop of the stable9 branch and not ontop of master. Otherwise it will merge all changes from master into stable9 ;)

Just try again 😃 If you need help - ping on IRC ;)

**Pull request merged**
