### PR TITLE
Add `email` and `generate-password` options in `occ user:add`

### PR DESCRIPTION
**Pull request by kyteinsky**
### ☑️ Resolves

* Update docs for: [server#40726](https://github.com/nextcloud/server/pull/40726)

### 🖼️ Screenshots

image

### CODE REVIEW

**Comment by joshtrichards** [comment]
Looks like this may need some minor adjustment to accommodate the final PR merged in server?

+`generate-password` coverage maybe?

**Comment by kyteinsky** [comment]
thanks for the heads up @joshtrichards !

**Comment by kyteinsky** [comment]
Didn't realise this was still unmerged. @blizzz Can you do a quick review and merge it? Here's the PR: https://github.com/nextcloud/server/pull/40726

**Review by come-nc — APPROVED** [review]

**Pull request merged**
