### PR TITLE
Add link to new phpdoc build

### PR DESCRIPTION
**Pull request by juliushaertl**
Fixes https://github.com/nextcloud/documentation/issues/1782

Needs backports once the stable server branch docs are deployed as well.

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:rocket: 

Can we – at some point – host this on a *.nextcloud.com domain?

**Comment by juliushaertl** [comment]
Sure either though https://docs.netlify.com/domains-https/custom-domains/ or we need to get a sysadmin to setup https://github.com/nextcloud/server/blob/master/build/phpDocumentor.sh to be deployed automatically somewhere. 

cc @rullzer @blizzz Any oppinion on that?

**Review by korelstar — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> Needs backports once the stable server branch docs are deployed as well.

What do you mean by this?

**Comment by juliushaertl** [comment]
I did setup the stable branches to be also built with netlify:

https://stable18--nextcloud-server.netlify.app/
https://stable19--nextcloud-server.netlify.app/

I'll take care of backporting this for the stable branches.

**Pull request merged**
