### PR TITLE
Improve migration docs

### PR DESCRIPTION
**Pull request by R0Wi**
* Add section on how migration classes are constructed
* Add a hint for "version" argument on "migrations:execute"

Signed-off-by: Robin Windey <ro.windey@gmail.com>

### CODE REVIEW

**Review by kesselb — APPROVED** [review]
Thanks :+1:

**Comment by kesselb** [comment]
I'm a bit unsure about the dependency injection part. Yes you can use dependency injection there. Probably not all services can constructed here.

**Comment by R0Wi** [comment]
> I'm a bit unsure about the dependency injection part. Yes you can use dependency injection there. Probably not all services can constructed here.

Well if i noticed it correctly, the migration classes are constructed via `\OC::$server`. So at least injecting a DB connection works. Not completely sure if everything can be injected but i don't see why not.

Will try to check this 👍

**Comment by kesselb** [comment]
> > I'm a bit unsure about the dependency injection part. Yes you can use dependency injection there. Probably not all services can constructed here.
> 
> Well if i noticed it correctly, the migration classes are constructed via `\OC::$server`. So at least injecting a DB connection works. Not completely sure if everything can be injected but i don't see why not.
> 
> Will try to check this +1

True True. I was probably a bit ambiguous. Usually migrations are executed when some kind of app update is happening. It's possible that old and new code is around. This may lead to weird states. My concern was/is that developers move to much logic to their migrations because they can. But not documenting that DI works there is also wrong.

**Pull request merged**
