### PR TITLE
Remove KDE docs

### PR DESCRIPTION
**Pull request by leonklingele**

### CODE REVIEW

**Comment by karlitschek** [comment]
makes sense 👍

**Comment by leonklingele** [comment]
I can't merge this. `master` is push-blocked. Please approve @LukasReschke @schiessle

**Comment by leonklingele** [comment]
`You're not authorized to merge this pull request.` 😿

**Comment by LukasReschke** [comment]
@leonklingele Try again :)

**Comment by leonklingele** [comment]
😻

**Comment by LukasReschke** [comment]
😘

**Pull request merged**
