### PR TITLE
Bugsbane master

### PR DESCRIPTION
**Pull request by nickvergessen**
Replaces #51 

Added one more commit to fix some warnings about headers

@MorrisJobke @Bugsbane

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@nickvergessen Could I ask you to fix the documentation make file:

```
$ (cd user_manual && make html-all)
sphinx-build -b html -D html_theme='owncloud_release' -d _build/doctrees   . _build/html/release
Making output directory...
Running Sphinx v1.2.3
loading pickled environment... not yet created

Theme error:
no theme named u'owncloud_release' found (missing theme.conf?)
```

**Comment by MorrisJobke** [comment]
👍

**Comment by Bugsbane** [comment]
So just to confirm, does anyone still need me to do anything?

**Comment by nickvergessen** [comment]
No, thanks for you patch thou!

**Comment by MorrisJobke** [comment]
@nickvergessen Do you mind to backport this? At least the packages page: https://docs.nextcloud.org/server/9/admin_manual/maintenance/package_upgrade.html

**Pull request merged**
