### PR TITLE
Update Oracle DB from Requirements page

### PR DESCRIPTION
**Pull request by mar1u5**
cc @LukasReschke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I guess we need to figure out if this is okay for customers first :see_no_evil: 

cc @karlitschek @jospoortvliet

**Comment by mar1u5** [comment]
Oracle is not compatible with Nextcloud at this time, because it was realized with an enterprise app.

**Comment by LukasReschke** [comment]
> Oracle is not compatible with Nextcloud at this time, because it was realized with an enterprise app.

It depends. Actually the whole Oracle logic lives in the server and the Enterprise app just set a config flag that enabled it.

That said, Oracle support is inherently broken. Many things do not work in the server properly, apps like calendar and contacts break as well, and PHP 7 has a broken Oracle adapter.

I really would advise anybody to stay away from using Nextcloud with Oracle. You enter a world of mainly untested pain ;-)

**Comment by karlitschek** [comment]
I don't think we should drop support for this at the moment without more information. Let's discuss again for the next major release.

**Comment by MorrisJobke** [comment]
@mar1u5 Could you adjust the text to state that the support needs to be contacted in advance to setup a Oracle based instance (*hint* Subscription is then needed *hint*)

**Comment by mar1u5** [comment]
Done 😉

**Comment by MorrisJobke** [comment]
Awesome :) Thanks :+1:

**Comment by MorrisJobke** [comment]
master f962503

**Pull request merged**
