### PR TITLE
Fix l10n bot

### PR DESCRIPTION
**Pull request by pierreozoux**
Then [this kind of PR](https://github.com/nextcloud/documentation/pull/7529) should be merged automatically.

### CODE REVIEW

**Review by p-bo — APPROVED** [review]
Seems safe - just dependencies versions bump

**Comment by pierreozoux** [comment]
@p-bo what do you mean?

**Comment by p-bo** [comment]
@pierreozoux sorry for making confusion - just tried to speed things up a bit...
(changed comment a bit to be more clear - should I remove it completely?)

**Review by nickvergessen — APPROVED** [review]

**Comment by pierreozoux** [comment]
Actually I though the sign-off was the missing part, but this PR was the missing part:
https://github.com/nextcloud/documentation/pull/8326

**Pull request merged**
