### PR TITLE
Obtain CSRF token

### PR DESCRIPTION
**Pull request by usselite**
Explanation for external clients on how to retrieve the CSRF token.

### CODE REVIEW

**Comment by rullzer** [comment]
Client should never fetch the CSRF token.
What are you trying to do that you need this in a client?

**Comment by usselite** [comment]
Creating guest accounts requires a CSRF check. Within the Outlook-addin I am trying to facilitate this option. See https://github.com/nextcloud/guests/blob/57062708251b418d09e03ee7bac4794c3c013f5a/lib/Controller/UsersController.php#L70

**Comment by rullzer** [comment]
> Creating guest accounts requires a CSRF check. Within the Outlook-addin I am trying to facilitate this option. See https://github.com/nextcloud/guests/blob/57062708251b418d09e03ee7bac4794c3c013f5a/lib/Controller/UsersController.php#L70

So that is actually invalid and not supported. Because without a session your CSRF token won't be valid anyways.

The real fix here is providing a real API endpoint in the guest app that clients can call ;)
I'll see what we can do there.

**Comment by usselite** [comment]
I actually do have a session in this case. But granted, the addition

**Pull request closed without merging**
