### PR TITLE
adding synch for Android

### PR DESCRIPTION
**Pull request by dacoex**
It should link to:
https://docs.nextcloud.com/android/android_app.html#sync-calendar-and-contacts

### CODE REVIEW

**Comment by dacoex** [comment]
Sorry this is not ready for release.
Do we actually want a dedicated sub-page for android?
I guess linking to the doc for the android would be sufficient

**Comment by skjnldsv** [comment]
@dacoex ah yes you're right!
Sorry I checked the user_manual but did not realized we were on the de section.
Yes, ideally everything should be translated :)

**Comment by dacoex** [comment]
Oh, it seems I should have created a issue first.
But I could not find the repo for the documentation as there are so many for Nextcloud & I did not want to have my issue forgotten.

To explain:
* the English page needs to be updated to reflect token-based access & auto-discovery from the Nextcloud app (it automatically enters the server id).
* then, the English page needs to be translated.

Reference:
https://github.com/nextcloud/documentation/blob/master/user_manual/pim/sync_android.rst

**Comment by skjnldsv** [comment]
Sure all fine :)
Can you do it? DO you need help?

**Comment by dacoex** [comment]
> Can you do it? DO you need help?
Yes, but need some time. Maybe in July.

But is this translation always manual?
This is how new pages from the English master get forgotten.

Can this be done more systematic?
There's this issue as well:
https://github.com/nextcloud/documentation/issues/216

**Pull request closed without merging**
