### PR TITLE
Fix images and alt tags, fix #621, fix #622

### LINKED ISSUE #621: Captions for figures
The style guide recommends creating a caption for every figure. This is standard practice--figures should have captions. However, the vast majority of figures in the documentation lack a caption. See the attached file.

Should the style guide be changed or should captions be added? 
[captions.zip](https://github.com/nextcloud/documentation/files/1523487/captions.zip)

### LINKED ISSUE #622: Image files with no alt tag
The documentation style guide says images "must have alt tags". The image files listed in the attached file lack alt tags. alt tags are usually similar or identical to captions so this issue can be addressed at the same time as #621.

[miss_alt.zip](https://github.com/nextcloud/documentation/files/1524250/miss_alt.zip)

### PR DESCRIPTION
**Pull request by jancborchardt**
- Change all `.. figure::` elements to `.. image::`
- Add empty `:alt:` so it is clear to screen readers that the images are decorative and don’t duplicate content
- Update styleguide with that info

Please review @peterdamian @tflidd @richardnixonafj @skjnldsv

### CODE REVIEW

**Review by Valdnet — APPROVED** [review]

**Comment by richardnixonafj** [comment]
What is the problem with the **figure::** tag?

The **:alt:** tag would not be responsible for maintaining accessibility for people with visual impairments?

**Comment by richardnixonafj** [comment]
**alt : text**
Alternate text: a short description of the image, displayed by applications that cannot display images, or spoken by applications for visually impaired users.

https://docutils.sourceforge.io/0.4/docs/ref/rst/directives.html#image

**Comment by jancborchardt** [comment]
> What is the problem with the figure:: tag?

Counter-question: Why use the `figure` tag when all of them are clearly images? :) In any HTML document, the `` tag would be used for all of them.

--------------

> The :alt: tag would not be responsible for maintaining accessibility for people with visual impairments?

Yes it would be, see https://www.a11yproject.com/posts/2013-01-14-alt-text/

> Use an empty `alt` attribute for any image that is decorative or not necessary for understanding the content of the page. For example, an image providing decoration to an article's heading could be hidden by giving the image an `alt=""` or simply `alt`

Otherwise, people using a screen reader will get info read out twice: Once as part of the text documentation, and once in slightly different form as alt text of a picture.

As example, just using the first item from the changeset here: https://github.com/nextcloud/documentation/pull/6393/files#diff-64596b21dca970c8e38f740a0125b239eb8943562fb13e742e9a1f82b6fc24b4L17-L18
The text "Apps page for enabling and disabling apps." is completely redundant for visually impaired people (or anyone else for that matter). The fact that there is an image depicting the page is not relevant.

**Review by pierreozoux — APPROVED** [review]
Lgtm

**Comment by richardnixonafj** [comment]
> > What is the problem with the figure:: tag?
> 
> Counter-question: Why use the `figure` tag when all of them are clearly images? :) In any HTML document, the `` tag would be used for all of them.
> 
> > The :alt: tag would not be responsible for maintaining accessibility for people with visual impairments?
> 
> Yes it would be, see https://www.a11yproject.com/posts/2013-01-14-alt-text/
> 
> > Use an empty `alt` attribute for any image that is decorative or not necessary for understanding the content of the page. For example, an image providing decoration to an article's heading could be hidden by giving the image an `alt=""` or simply `alt`
> 
> Otherwise, people using a screen reader will get info read out twice: Once as part of the text documentation, and once in slightly different form as alt text of a picture.
> 
> As example, just using the first item from the changeset here: https://github.com/nextcloud/documentation/pull/6393/files#diff-64596b21dca970c8e38f740a0125b239eb8943562fb13e742e9a1f82b6fc24b4L17-L18
> The text "Apps page for enabling and disabling apps." is completely redundant for visually impaired people (or anyone else for that matter). The fact that there is an image depicting the page is not relevant.

Really, you're right.

**Review by richardnixonafj — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> The backport to stable21 failed. Please do this backport manually.

@jancborchardt Mind to look into this?

**Comment by jancborchardt** [comment]
Backport at https://github.com/nextcloud/documentation/pull/6445

**Comment by MorrisJobke** [comment]
> Backport at #6445

Thx

**Pull request merged**
