### PR TITLE
Speech-To-Text and Machine Translation providers with user context

### PR DESCRIPTION
**Pull request by andrey18106**
Describe provider with userId usage for Machine Translation (https://github.com/nextcloud/server/pull/42649) and Speech-To-Text (https://github.com/nextcloud/server/pull/42761), similar to Text Processing for consistency between them.

### Speech-To-Text

image

### Machine Translation
image

### CODE REVIEW

**Comment by nickvergessen** [comment]
Please also add to https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_29.html#id1

**Comment by ChristophWurst** [comment]
> Please also add to https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_29.html#id1

IMO upgrade docs are not necessary for a *new* API. If you have an existing app you don't need to do anything about this to keep the app alive.

**Comment by nickvergessen** [comment]
> IMO upgrade docs are not necessary for a new API. If you have an existing app you don't need to do anything about this to keep the app alive.

My understanding of that thing was to have a "quick overview" of things you could add to your app, without having to grep the docs repo for "New in version 29" or checking all files touch-date.
Maybe you considered implementing a STT provider but the missing context prevented you from doing so?

**Comment by ChristophWurst** [comment]
Fair point

My inspiration was https://laravel.com/docs/9.x/upgrade. If we list everything, the important changes can be hard to find. We could have a dedicated section for announcements of new APIs?

**Comment by bigcat88** [comment]
_Can we not add this time to the “new APIs”, we are not sure how long these classes will be there, this will be decided by team and Marcel, perhaps in the near future we will make a system where providers are immediately located in exApp and will move away from using these classes through the process of deprication._

**Comment by nickvergessen** [comment]
> Can we not add this time to the “new APIs”, we are not sure how long these classes will be there, this will be decided by team and Marcel, perhaps in the near future we will make a system where providers are immediately located in exApp and will move away from using these classes through the process of deprication.

It's OCP, so our deprecation period is 3 years?

**Pull request merged**
