### PR TITLE
Translation User Manual En to Pt-BR

### PR DESCRIPTION
**Pull request by sirpresident**
@fgsl

### CODE REVIEW

**Comment by sirpresident** [comment]
Guys, sorry for the mess of creating other PR, I was trying to find a way to make it easier to review, @ fgsl advised me about it.

**Old**
Add user manual pt-br #1318
Add User Manual Pt-br #1277

**Comment by fgsl** [comment]
I recommend to follow my suggestion in https://github.com/nextcloud/documentation/pull/1328#commitcomment-32879917:

> I make a suggestion: open a issue for each file and send one by one. This cause less fear to developers and make easier to do review and integrate to master.

The commit "Create Folder" has 209 files. It is better that each commit has few files to make easy the review. I think that it must there is one commit by issue.

**Comment by sirpresident** [comment]
> 
> 
> I recommend to follow my suggestion in [#1328 (comment)](https://github.com/nextcloud/documentation/pull/1328#commitcomment-32879917):
> 
> > I make a suggestion: open a issue for each file and send one by one. This cause less fear to developers and make easier to do review and integrate to master.
> 
> The commit "Create Folder" has 209 files. It is better that each commit has few files to make easy the review. I think that it must there is one commit by issue.

okay, I'll review all the files and adjust them as you go by posting the commits!

**Comment by enoch85** [comment]
Thanks a ton for this! Now I have a reason to introduce my wife to Github (she's Brazilian). :D

**Pull request merged**
