### PR TITLE
note on the redis socket file permissions

### PR DESCRIPTION
**Pull request by jospoortvliet**
This can take forever to debug ;-)

### CODE REVIEW

**Comment by tflidd** [comment]
I still avoid having 777 permissions. So I put the webserver-user in the redis-group and use 770 socketpermissions.

**Comment by blizzz** [comment]
> I still avoid having 777 permissions. So I put the webserver-user in the redis-group and use 770 socketpermissions.

Agreed, I am doing the same.

**Comment by jospoortvliet** [comment]
Perfectly valid point, I modified the instructions to advise to put the web server user in the redis group instead of changing the permissions.

**Comment by jospoortvliet** [comment]
Thanks @MorrisJobke !!!

**Pull request merged**
