### PR TITLE
Add @PublicPage to get() method tags

### PR DESCRIPTION
**Pull request by skaramicke**
I could not get this example to work without adding @PublicPage to the PublicAPIController->get() method. In fairness, my implementation only validates token, and returns false in isPasswordProtected.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@ChristophWurst Should we also adjust the text around this? cc @skjnldsv

**Comment by skjnldsv** [comment]
cc @juliushaertl

**Comment by ChristophWurst** [comment]
> @ChristophWurst Should we also adjust the text around this? cc @skjnldsv

Which part specifically?

**Comment by MorrisJobke** [comment]
Adding a section that describes that the `get` method needs to be annotated like this to allow unauthenticated access to it.

**Comment by ChristophWurst** [comment]
Sure that won't hurt.

**Comment by nickvergessen** [comment]
Rebased in https://github.com/nextcloud/documentation/pull/8092

**Pull request closed without merging**
