### PR TITLE
Remove obsolete HOME and HTTP_HOME variables from Apache2 config

### PR DESCRIPTION
**Pull request by MichaIng**
Additionally align format for Debian/Ubuntu and CentOS/RHEL configs:
- Consistent spacing and order
- No double quotes around directory path which does not contain spaces

Fixes: #1798

Signed-off-by: MichaIng <micha@dietpi.com>

### CODE REVIEW

**Comment by MichaIng** [comment]
@juliangehring @ChristophWurst 
Shall we backport this? Not something important, but doesn't hurt?

**Comment by ChristophWurst** [comment]
fine by me :)

**Pull request merged**
