### PR TITLE
enh(dev/TextProcessing): Add docs for IProviderWithUserId, IProviderWithExpectedRuntime and Imanager#runOrSchedule

### PR DESCRIPTION
**Pull request by marcelklehr**
### ☑️ Resolves

* Docs for https://github.com/nextcloud/server/pull/41271

### 🖼️ Screenshots

image

### CODE REVIEW

**Comment by blizzz** [comment]
Please don't forget to set milestone and labels when opening a PR :smiley:

**Review by julien-nc — CHANGES_REQUESTED** [review]
:+1:

**Comment by blizzz** [comment]
master is 29

**Review by julien-nc — APPROVED** [review]
:+1:

**Pull request merged**
