### PR TITLE
Update categories in info.rst

### PR DESCRIPTION
**Pull request by bakkegaard**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@BernhardPosselt for the completeness of this list

**Comment by MorrisJobke** [comment]
The category must be one of:

* auth
* customization
* files
* games
* integration
* monitoring
* multimedia
* office
* organization
* social
* tools

See https://nextcloudappstore.readthedocs.io/en/latest/developer.html#info-xml (scroll down to category)

**Comment by bakkegaard** [comment]
Ah, okay. I took the list from the drop-down on https://apps.nextcloud.com/developer/apps/generate .

**Comment by MorrisJobke** [comment]
Those are the keywords that are supported ;) the drop down is the human readable version ;)

**Comment by bakkegaard** [comment]
Makes sense. Is it okay now?

**Comment by MorrisJobke** [comment]
stable12 7776ca5a
stable11 e4c93a84

**Comment by MorrisJobke** [comment]
Thank you @bakkegaard for this contribution 👍

**Pull request merged**
