### PR TITLE
Add option for incoming shares for transfer ownership

### PR DESCRIPTION
**Pull request by PVince81**
From https://github.com/nextcloud/server/pull/28118

### CODE REVIEW

**Comment by acsfer** [comment]
https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/occ_command.rst#file-operations should be updated too.

**Comment by PVince81** [comment]
> https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/occ_command.rst#file-operations should be updated too.

thanks for pointing out.
I wasn't expecting duplicate pages :sweat_smile:

**Comment by PVince81** [comment]
ah, it's the same page. ok, saw the note, will update

**Comment by PVince81** [comment]
@acsfer I've adjusted the command summary

**Review by acsfer — APPROVED** [review]

**Pull request merged**
