### PR TITLE
Fix order of Nginx config options

### PR DESCRIPTION
**Pull request by MorrisJobke**
See https://github.com/nextcloud/server/issues/237#issuecomment-229923262

### CODE REVIEW

**Comment by mar1u5** [comment]
Should be fine now 😉

**Comment by mar1u5** [comment]
could you port this to `stable9` 😉 @MorrisJobke

**Comment by MorrisJobke** [comment]
stable9 948655d and bfc032b

**Comment by MorrisJobke** [comment]
> could you port this to stable9 😉 @MorrisJobke

I was already on this :)

**Comment by mar1u5** [comment]
👍

**Pull request merged**
