### PR TITLE
fix(admin): refine .mjs related NC28 upgrade info

### LINKED ISSUE #11429: Add mjs to upgrade guide for admins
### Thanks for helping improve our documentation! 

* There is always room for improvement!
* All contributions (changes and change ideas) - from the largest **to the tiniest** - help make Nextcloud better and easier to use!

---

Nextcloud 27 added support for `mjs` and with Nextcloud 28, some core components started to make use of it. This was a breaking change for webserver setups without Apache2 or when not making use of `.htaccess`, since requests to those files were rewritten to `index.php`. It would be beneficial to add a hint for admins to the upgrade guide of the docs: https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_28.html 

---

#### Notes

* Please be patient: this is a large open source project that is overseen by a mixture of volunteers and non-volunteers which are all ultimately busy.
* If your suggestion is a troubleshooting scenario or one you're not 100% certain about, please post for feedback on the [Nextcloud Help Forum](https://help.nextcloud.com) first.
  - *Then* return here to bring back your experience to help improve the documentation for clarity, etc. (and link back to the forum discussion in your report!)

#### Protip: If you want to help move things along (or just help out in other ways too) here are some suggestions:
* Look for areas where you can assist - even seemingly unrelated areas - *because doing so frees up resources for your favorite topics and ideas*.
* Submit a proposed change - that attempts to addresses your issue - as a pull request.
* Participate in a discussion on some other unresolved [submitted idea ("issues")](https://github.com/nextcloud/documentation/issues) to help move it along.
* Post a comment or review on someone else's [proposed change ("pull request")](https://github.com/nextcloud/documentation/pulls) to help move it along.

### PR DESCRIPTION
**Pull request by MichaIng**
To cover rewrites, Cache-Control header, and give a concrete config file for MIME types, as suggested here: https://github.com/nextcloud/documentation/pull/11471#issuecomment-1912212928

### ☑️ Resolves

* Fix #11429

### CODE REVIEW

**Review by kesselb — APPROVED** [review]

**Comment by kesselb** [comment]
Thank you :+1:

**Comment by MichaIng** [comment]
I am currently building it for a screenshot, just to be sure the nested list looks fine.

**Review by st3iny — APPROVED** [review]

**Comment by st3iny** [comment]
Damn, need to wait for the other backports ...

**Comment by MichaIng** [comment]
Makes sense, they are currently blocked by "Block merges during freezes", hence needs someone with more permissions.

**Pull request merged**
