### PR TITLE
Update background_jobs_configuration.rst

### PR DESCRIPTION
**Pull request by Steve8291**
Adjust `nextcloudcron.service` to wait for `mysql.service` dependency before starting. This prevents errors during a reboot.  
This references: https://github.com/nextcloud/documentation/issues/1584#issuecomment-524545159

### CODE REVIEW

**Comment by Steve8291** [comment]
On Ubuntu both mariadb and MySQL are covered by the mysql.service so there is no need to add anything additional. I don’t know about pgsql but I’ll try to find out. Either way I’ll adjust with a comment to change the code based on your database.

**Comment by skjnldsv** [comment]
Thanks a lot @Steve8291 :)

**Comment by Steve8291** [comment]
@skjnldsv I've made the changes. I don't need to do another pull request do I?

**Comment by kesselb** [comment]
Thanks :+1: 

I'm not an systemd expert but adding a dependency to mysql or pqsql is wrong way to fix it. 

> The important parts in the timer-unit are OnBootSec and OnUnitActiveSec. OnBootSec will start the timer 5 minutes after boot, otherwise you would have to start it manually after every boot. OnUnitActiveSec will set a 5 minute timer after the service-unit was last activated.

Why is this not working? I think the Install section within the service definition is the problem here. It says the nextcloud cron is requested to be started during boot. 

> For each .timer file, a matching .service file exists (e.g. foo.timer and foo.service). The .timer file activates and controls the .service file. The .service does not require an [Install] section as it is the timer units that are enabled. If necessary, it is possible to control a differently-named unit using the Unit= option in the timer's [Timer] section. 

From https://wiki.archlinux.org/index.php/Systemd/Timers. Removing the Install section from the service definition should do the trick. On very slow instances the OnBootSec needs a higher value but 5min should work fine for most systems.

**Comment by Steve8291** [comment]
Thanks @kesselb that sounds like a better way to fix the errors.  
I just tested this on my server and it works. No errors after a reboot and the timer is doing its job.  
nextcloudcron.service now looks like this:  
```
[Unit]
Description=Nextcloud cron.php job

[Service]
User=www-data
ExecStart=/usr/bin/php -f /var/www/nextcloud/cron.php
```
Might need to add a note in the documentation that you don't run `systemctl enable nextcloudcron.service` anymore but only enable the timer.

**Comment by skjnldsv** [comment]
> Might need to add a note in the documentation

Could you add this? :) :bowing_woman:

**Comment by Steve8291** [comment]
Should I create a new pull request or just modify this one?

**Comment by kesselb** [comment]
Modify this one. Could you add another note like "heads up the service file does not need the Install section. Please check your setup because we recommended it in earlier versions". I guess the wording needs some tweaking.

**Comment by kesselb** [comment]
Thanks @Steve8291 :rocket:

**Pull request merged**
