### PR TITLE
document that 64bit is required

### PR DESCRIPTION
**Pull request by szaimen**
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by MichaIng** [comment]
Would it be an idea to add some more details about what might not "run well" with 32-bit?

I see that it's better to declare 64-bit as dependency instead of having 32-bit systems running into the couple of long outstanding bugs without proper fixes. But many Nextcloud instances run on 32-bit ARM systems now (including my personal one), and many users will decide to install Nextcloud on 32-bit regardless, as it obviously works until you hit the 2 GiB/3 GiB size limit at some places/for some tasks.

So while we cannot provide support, as not all potential issues with 32-bit are known exactly (with all apps), at least we provide users with the well known issues they should be prepared for, when keep using Nextcloud on their 32-bit system or insist installing it to one.

Most importantly it's the download size limit for multiple files and overall trashbin size limit, right?

**Comment by szaimen** [comment]
> Most importantly it's the download size limit for multiple files and overall trashbin size limit, right?

yes

> So while we cannot provide support, as not all potential issues with 32-bit are known exactly (with all apps), at least we provide users with the well known issues they should be prepared for, when keep using Nextcloud on their 32-bit system or insist installing it to one.

Feel free to open a PR that adds a bit more detail to this 👍

**Pull request merged**
