### PR TITLE
Fix Backslahes with Backquotes

### PR DESCRIPTION
**Pull request by wonderfulShrineMaidenOfParadise**
Without backquotes it will be displayed as HKEY_LOCAL_MACHINESYSTEMCurrentControlSetServicesWebClientParameters

### CODE REVIEW

**Comment by CarlSchwan** [comment]
Hi, thanks for your commit. Could you signof your commit and squash it? See https://github.com/nextcloud/documentation/pull/6956/checks?check_run_id=3041210280

**Comment by wonderfulShrineMaidenOfParadise** [comment]
@CarlSchwan Okay I updated it.

**Review by CarlSchwan — APPROVED** [review]

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
