### PR TITLE
Added example rule to exclude folder

### PR DESCRIPTION
**Pull request by GAS85**
Seems it was always asked about.
Picture download screenshot via https://gas85.ddns.net/index.php/s/TQ3Q9omcBRQsPFr and upload it to /images/

### CODE REVIEW

**Comment by skjnldsv** [comment]
> Picture download screenshot via [gas85.ddns.net/index.php/s/TQ3Q9omcBRQsPFr](https://gas85.ddns.net/index.php/s/TQ3Q9omcBRQsPFr) and upload it to /images/

Please add it yourself?
You can add files to your fork

**Comment by GAS85** [comment]
I did not know how to added file from the quick edit view....

**Comment by skjnldsv** [comment]
But everything was fine, what is the issue?

**Comment by MorrisJobke** [comment]
> I did not know how to added file from the quick edit view....

The file was there already. 👍 So we just needed to approve it and then it could have went in :)

**Comment by GAS85** [comment]
I seen few tickets about how to exclude folder from the tagging. It was also not clear for me, so seems to be added.
With a file I just click on edit, and did not noticed that it was forked to my account. So I thought that I only could edit current file, but not added screenshot.

**Comment by GAS85** [comment]
Sorry, should I reopen it?

**Comment by GAS85** [comment]
Thanks!

**Pull request merged**
