### PR TITLE
Update external_storage_configuration_gui.rst

### LINKED ISSUE #1925: Update external storage images
The unmaintained backends (Dropbox etc) were removed from text #1891 but the images still references them, which is confusing. I'm willing to take a stab.

https://docs.nextcloud.com/server/18/admin_manual/configuration_files/external_storage_configuration_gui.html

image

### PR DESCRIPTION
**Pull request by joshmorel**
To resolve #1925

@skjnldsv This updates the screenshots to remove Dropbox etc - it definitely applies back to 16. Not sure about 15.

I noticed "Mount options" is also quite different with v16+ so I changed that in the 2nd commit of this PR:

image

Nothing else seemed too different (some screenshots with older design but similar enough) however maybe a quick look through by the main person responsible for with apps/files_external  might be worthwhile?

### CODE REVIEW

**Comment by skjnldsv** [comment]
Ah wait, we merged a bit too fast ^^'

@joshmorel where are your new images used in the docs? I don't see any reference so far?

**Comment by joshmorel** [comment]
@skjnldsv 

All the new images - are replacing existing files referenced in:

https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_files/external_storage_configuration_gui.rst

Lines:
33: .. figure:: external_storage/images/add_storage.png
91: .. figure:: external_storage/images/mount_options.png
131: .. figure:: external_storage/images/user_mounts.png

**Comment by skjnldsv** [comment]
Ah sorry, I misunderstood github, I thought those were new files, not modified ones! All good! :grin: 
Thanks a lot for this!

**Comment by joshmorel** [comment]
@skjnldsv 

NP. Like https://github.com/nextcloud/documentation/pull/1891 this can be backported to v16. I supposed to call those slash commands as the contributor or you as the maintainer?

**Comment by skjnldsv** [comment]
@joshmorel you can also do it by commenting like this

/backport to stable18

**Pull request merged**
