### PR TITLE
[stable9] revise updater.server.url to reflect nextcloud.org URL

### PR DESCRIPTION
**Pull request by hailthemelody**
Please see https://github.com/nextcloud/documentation/pull/18 for more info

With thanks to @MorrisJobke and @mar1u5 for their help!

### CODE REVIEW

**Comment by mar1u5** [comment]
👍

**Comment by hailthemelody** [comment]
Noob aside question - I forgot to add my user.name and user.email on the original commits (docs and server). Is there an easy-ish way to add these? I've tried a few things from online documentation but it gets complicated quick. I can let it go, the project it the priority.

**Comment by mar1u5** [comment]
See here: https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

I'm sorry but I think it is not possible to add your email afterwards 😁 ...Maybe one of the **Git pros** here (yeah ... I mean you @MorrisJobke 😜) does know a way 😉

**Comment by MorrisJobke** [comment]
> Maybe one of the Git pros here (yeah ... I mean you @MorrisJobke 😜) does know a way 😉

I know a way, but this means rewriting git history. I would not do it and leave it as it is. Is this okay for you? Otherwise we need to do some git magic.

**Comment by hailthemelody** [comment]
Thank you, though it's not worth the amount of time it would take for the group. I'll let it go.

**Pull request merged**
