### PR TITLE
Update supported apps

### PR DESCRIPTION
**Pull request by MariusBluem**
- Added links to code of the specific app to better find it
- Changed display names of the specific apps

**Questions:**

- Any apps to add/remove? (e.g. user_external)
- What is `Collaborative Tags` / GitHub link?
- What is `Update Notifications` / GitHub link?

Signed-off-by: Marius Blüm <marius@lineone.io>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> * What is `Update Notifications` / GitHub link?

https://github.com/nextcloud/server/tree/master/apps/updatenotification

> * What is `Collaborative Tags` / GitHub link?

https://github.com/nextcloud/server/tree/master/apps/systemtags

**Comment by MorrisJobke** [comment]
> * Any apps to add/remove? (e.g. user_external)

I guess this one can go.

**Comment by MariusBluem** [comment]
Done. Please review!

**Pull request merged**
