### PR TITLE
Master of docs is stable13 manual

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @juliushaertl

### CODE REVIEW

**Comment by juliushaertl** [comment]
Is there no stable13 branch for documentation? Because I'd say we should keep this on master for the master branch and just change for the individual release branches.

**Comment by MorrisJobke** [comment]
> Is there no stable13 branch for documentation? Because I'd say we should keep this on master for the master branch and just change for the individual release branches.

No, because usually there happens a lot of documentation after the release and it thus avoids the mass backport of all the tiny things.

**Comment by MorrisJobke** [comment]
I'm fine with reverting this once we split out stable13.

**Comment by juliushaertl** [comment]
Ok, fine then :+1:

**Pull request merged**
