### PR TITLE
fix(s3): document options for adjusting multipartcopy behavior

### PR DESCRIPTION
**Pull request by joshtrichards**
Added in nextcloud/server#41914

### ☑️ Resolves

* Fixes `pending documentation` label on nextcloud/server#41914

### CODE REVIEW

**Review by come-nc — APPROVED** [review]
But more documentation about this would be good. Related PR says "Multipart copy seems problematic with some backends so avoid it when possible.".
That should be reflected in the documentation, maybe with a list of which backends have problems or how to detect it?

**Review by juliusknorr — APPROVED** [review]

**Pull request merged**
