### PR TITLE
Add traefik v2.0 configuration example

### PR DESCRIPTION
**Pull request by josefglatz**

### CODE REVIEW

**Comment by kesselb** [comment]
Mind to sign off your commits? https://github.com/nextcloud/documentation/pull/1519/checks?check_run_id=159637943 for the right commands.

**Comment by josefglatz** [comment]
> Looks good to me but can't test

Since the config has changed and you have to add the redirect via middlewares, I can also post a complete working configuration for my docker-compose service.

**Comment by skjnldsv** [comment]
> I can also post a complete working configuration for my docker-compose service.

Maybe this should go into https://github.com/nextcloud/docker?
I'm wondering if we should have a docker section in our docs. Though we don't officially support it :thinking:

**Comment by kesselb** [comment]
@josefglatz please sign off your commits: https://github.com/nextcloud/documentation/pull/1519/checks?check_run_id=159637943

**Comment by MorrisJobke** [comment]
Duplicate of #1872

**Comment by MorrisJobke** [comment]
Sorry that we missed that one here.

**Pull request closed without merging**
