### PR TITLE
Add OpenAPI workflow to confirm it's working

### PR DESCRIPTION
**Pull request by nickvergessen**
### ☑️ Resolves

* CI for #11314

### CODE REVIEW

**Comment by nickvergessen** [comment]
Failing run on stable28 before the merge of #11315 
https://github.com/nextcloud/documentation/actions/runs/7005702281/job/19055942324

**Comment by provokateurin** [comment]
This doesn't make much sense because it breaks silently and not due to PR changes. The only real solution is https://github.com/nextcloud/documentation/issues/11318

**Comment by nickvergessen** [comment]
> This doesn't make much sense because it breaks silently and not due to PR changes.

It would still notify us that the next release build will be broken.
But yeah #11318 is much better.

**Comment by provokateurin** [comment]
> It would still notify us that the next release build will be broken.

In that case running it as a cron would make more sense since none of the PRs will be the cause of the breakage and it would unnecessarly block merging fine PRs.

**Review by provokateurin — APPROVED** [review]

**Pull request merged**
