### PR TITLE
Fix semanage argument and add recursion and verbose for restorecon

### PR DESCRIPTION
**Pull request by ayamshanov**
Files in "apps/", "config/", "data/" stay unconfigured after steps from current instruction.

_Example:_

Create lab environment (check, that all is not configured):
`# cat /etc/centos-release`
`CentOS Linux release 7.2.1511 (Core)`
`# mkdir -p /my/test/path`
`# touch /my/test/path/and_test_file.txt`
`# semanage fcontext -l | grep /my/test/path`
`#`

---

Configure by instruction from docs (file 'and_test_file.txt' stay unconfigured):
`# semanage fcontext -a -t httpd_sys_rw_content_t '/my/test/path'`
`# semanage fcontext -l | grep /my/test/path`
`/my/test/path                                      all files          system_u:object_r:httpd_sys_rw_content_t:s0`
`# ls -Z /my/test/path/`
`# restorecon -Rv /my/test/path`
`restorecon reset /my/test/path context unconfined_u:object_r:default_t:s0->unconfined_u:object_r:httpd_sys_rw_content_t:s0`
`# ls -Z /my/test/path/`
`-rw-r--r--. root root` **unconfined_u:object_r:default_t:s0** `and_test_file.txt`
`#`

---

Delete previous setting (check, that all is not configured):
`# semanage fcontext -d -t httpd_sys_rw_content_t '/my/test/path'`
`# semanage fcontext -l | grep /my/test/path`
`#`

---

Configure by new version of instruction (file 'and_test_file.txt' now is configured too):
`# semanage fcontext -a -t httpd_sys_rw_content_t '/my/test/path(/.*)?'`
`# semanage fcontext -l | grep /my/test/path`
`/my/test/path(/.*)?                                all files          system_u:object_r:httpd_sys_rw_content_t:s0`
`# restorecon -Rv /my/test/path`
`restorecon reset /my/test/path/and_test_file.txt context unconfined_u:object_r:default_t:s0->unconfined_u:object_r:httpd_sys_rw_content_t:s0`
`# ls -Z /my/test/path/`
`-rw-r--r--. root root` **unconfined_u:object_r:httpd_sys_rw_content_t:s0** `and_test_file.txt`
`#`

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by ayamshanov** [comment]
One more thing: 

Maybe for first clean installation it's enough. But if you recreate some files (or copy config.sample.php to config.php; or restore files from backup, or migrate from anywhere) you must have correct SELinux configuration and rerun `restorecon -R ...`.

**Comment by nickvergessen** [comment]
I'm willing to blindly merge this, but would be nice if someone could confirm

**Comment by AelricRiggs** [comment]
@nickvergessen 
I can confirm that on my CentOS 7 server with selinux enabled I still got unable to write errors using the current version of the commands, but that the install works flawlessly with these new commands. All this change does is make sure that the context change is recursive, so not just the folders get changed.

**Comment by nickvergessen** [comment]
Thanks @AelricRiggs

**Pull request merged**
