### PR TITLE
Update nginx.rst

### PR DESCRIPTION
**Pull request by moviuro**
Avoid leaking `X-Powered-By`
Add link to a sane nginx TLS configuration

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Thanks 👍

**Comment by moviuro** [comment]
Something similar should be done on the other reverse proxy templates (Apache for instance).

**Comment by MorrisJobke** [comment]
Could you prepare patches for this as well?

**Comment by MorrisJobke** [comment]
stable14 4afa8ae5
stable13 60b02d54

**Pull request merged**
