### PR TITLE
Some more cleanup

### LINKED ISSUE #73: Errors from s//
`using the Nextcloud / Nextcloud Desktop Sync Client`
https://docs.nextcloud.org/server/10/user_manual/

Use of the upstream was intended.

### PR DESCRIPTION
**Pull request by nickvergessen**
@LukasReschke @MorrisJobke 

Should backport both commits, 6ccd2c5678b85d35a8673d784bef5c6c89e7ecb9 and this one to 10 and 9?

Fix #73

### CODE REVIEW

**Comment by LukasReschke** [comment]
👍

**Comment by MorrisJobke** [comment]
👍

**Comment by MorrisJobke** [comment]
stable10 5ccfc98

**Comment by MorrisJobke** [comment]
table9 33670ba and c928980

**Pull request merged**
