### PR TITLE
Remove reference to not existing file

### PR DESCRIPTION
**Pull request by MorrisJobke**
Ref https://github.com/nextcloud/server/issues/2686#issuecomment-267335756

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
Should we add something like check core/l10n/ instead? Otherwise someone might add "Deutsch"?

**Comment by MorrisJobke** [comment]
I would say that we should list the underlying ISO standard and a link to the Wikipedia page of it.

**Comment by nickvergessen** [comment]
That's awesome

**Comment by nickvergessen** [comment]
Backport to stable11

**Comment by MorrisJobke** [comment]
> Backport to stable11

#302

**Pull request merged**
