### PR TITLE
Document new updater

### PR DESCRIPTION
**Pull request by MorrisJobke**
Please proofread

bildschirmfoto am 2017-05-14 um 17 58 43-fullpage

### CODE REVIEW

**Comment by MariusBluem** [comment]
Can you remove the "Nextcloud" in Update **Nextcloud** with the **Nextcloud** Updater Headline 😬 I like the macOS Safari-screenshots 👍🙈

**Comment by MorrisJobke** [comment]
Headline is fixed in my other PR

**Comment by MorrisJobke** [comment]
https://docs.nextcloud.com/server/12/admin_manual/maintenance/update.html 🙌

**Comment by MorrisJobke** [comment]
stable11 00b73c3b

**Comment by MorrisJobke** [comment]
stable10 06964ab1] Document new updater
 Date: Sun May 14

**Pull request merged**
