### PR TITLE
Update to *disableuser* and *enableuser*

### PR DESCRIPTION
**Pull request by ds4a**
Addition to examples for **users / disableuser** and **users / enableuser**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I opened a ticket in the server repo: https://github.com/nextcloud/server/issues/3890

Maybe it's a bug in the code.

**Comment by ds4a** [comment]
Will await the outcome of [nextcloud/server#3890](https://github.com/nextcloud/server/issues/3890). Thanks for submitting that.

**Comment by MorrisJobke** [comment]
This is only needed in stable11 - master will have a fixed behaviour.

**Comment by MorrisJobke** [comment]
I cherry picked this to stable11: stable11 c93e4a3b

**Comment by ds4a** [comment]
This (c93e4a3) would seem the most logical and user friendly outcome for stable 11. Thanks.

**Pull request closed without merging**
