### PR TITLE
Add mapfile serving for nginx conf examples

### PR DESCRIPTION
**Pull request by skjnldsv**
It got lost  🙄

https://github.com/nextcloud/documentation/pull/1504

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Comment by szaimen** [comment]
@skjnldsv do you mind adding this also to the .htaccess file?
https://github.com/nextcloud/server/blob/master/.htaccess

**Comment by szaimen** [comment]
Otherwise I fear this will remain broken for native apache instances...

**Comment by skjnldsv** [comment]
> @skjnldsv do you mind adding this also to the .htaccess file? [https://github.com/nextcloud/server/blob/master/.htaccess](https://github.com/nextcloud/server/blob/master/.htaccess?rgh-link-date=2022-02-25T13%3A34%3A41Z)

I  thought we had that already :face_exhaling:

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/blob/22a9c54f89ac863abc6320f5db21436f41c56a19/lib/private/Setup.php#L531 
Ok, why :facepalm:

**Comment by skjnldsv** [comment]
Yeah, it seems done already then.
If you have `htaccess.RewriteBase` properly configured (by default), then it's fine

**Comment by skjnldsv** [comment]
> @skjnldsv do you mind adding this also to the .htaccess file? [https://github.com/nextcloud/server/blob/master/.htaccess](https://github.com/nextcloud/server/blob/master/.htaccess?rgh-link-date=2022-02-25T13%3A34%3A41Z)

Also, those lines onlyadd caching, which we probably don't want for map files :wink:

**Comment by szaimen** [comment]
Right, so I guess with apache it should already work?

**Pull request merged**
