### PR TITLE
Harden NGINX config

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by jknockaert** [comment]
I think a feature of nginx was overlooked in this PR. By adding `try_files` the variable `$fastcgi_path_info` is reset:
https://trac.nginx.org/nginx/ticket/321
So the fastcgi parameter `PATH_INFO` will get a different value because of adding `try_files` to the config.
This can be solved by adding `set $path_info $fastcgi_path_info;` before `try_files`, and then assigning `$path_info` to `PATH_INFO`.

**Comment by rullzer** [comment]
@jknockaert could you submit a PR?

**Comment by jknockaert** [comment]
@rullzer #1679

**Pull request merged**
