### PR TITLE
feat(docs): Add a "copy" button to code blocks

### PR DESCRIPTION
**Pull request by joshtrichards**
### ☑️ Resolves

This makes it easy to copy and paste config files, snippets, and code examples. Pretty self explanatory.

https://github.com/executablebooks/sphinx-copybutton

### 🖼️ Screenshots

image

image

### CODE REVIEW

**Review by susnux — APPROVED** [review]
Nice!

**Comment by nickvergessen** [comment]
Woho :tada: 
Thanks a lot

**Pull request merged**
