### PR TITLE
PHP upgrade for 5.6 and 7.0 on RHEL/CentOS

### PR DESCRIPTION
**Pull request by michag86**
Fix fox #291

I have tested PHP 7 on CentOS 7. 
The path informations for PHP 5.6 are copied from the rpms from 
http://mirror.centos.org/centos/6/sclo/x86_64/rh/rh-php56/
http://mirror.centos.org/centos/7/sclo/x86_64/rh/rh-php56/

Can somebody check this?
@tflidd @lamixer

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@oparoz Weren't you interested in this lately?

**Comment by oparoz** [comment]
Thanks for the heads up @MorrisJobke :)

**Comment by oparoz** [comment]
I've tested the instructions and the biggest problem is that it's aimed at people already running PHP and Apache.
Those are upgrade instructions and not installation instructions.

**Comment by michag86** [comment]
@oparoz What do you think about changing "Disable loading the old PHP 5.3 Apache module" to "Disable loading the old PHP 5.3 Apache module (only required if php is already installed)"?

**Comment by MorrisJobke** [comment]
@oparoz @karlitschek Would be nice to get some testing on this. At least we say to support this and should be happy about this nice writeup 😉

**Comment by tflidd** [comment]
This topic is stuck, would be a pity to lose this contribution. I asked on the forum for CentOS users to help us reviewing this issue:
https://help.nextcloud.com/t/php-7-on-centos-install-instructions-are-updated-review-needed/27732

**Comment by michag86** [comment]
I've tested and used 5.6.
I can also add the instructions for PHP 7.1.

**Comment by KB7777** [comment]
Wouldn't be better to use remi repo for PHP7.x for CentOS7?
Installation is very easy -- https://help.nextcloud.com/t/what-is-the-supported-php7-installation-method-for-centos-7/9832/25?u=therion7777

Works fine at my NC instance from NC11-NC13 versions for few k users.

**Comment by oparoz** [comment]
I agree that using Remi's repo would be the more universal solution.

**Comment by michag86** [comment]
https://wiki.centos.org/de/AdditionalResources/Repositories/
Software Collections (SCL) is listes as Additional CentOS Provided Repositories and Remi is listed as Community Approved Repositories, so I decided to use SCL.

The manual for updating to newer php version for centos/rhel was also referencing to scl.
I think SCL is the "supported" source for newer php versions on rhel/centos.

**Comment by tflidd** [comment]
It's now over a year. It's really missing in the documentation and there were no principal objections. And if it is really a matter of personal preference, we could perhaps link to a place with some comparison of the different ways to handle newer php versions e.g. https://www.hogarthuk.com/?q=node/15 (found on the page @michag86 linked)

**Pull request merged**
