### PR TITLE
Added note on apc.enable_cli for system Cron based configs

### LINKED ISSUE #7051: System Cron job (doc) is missing extra parameter for APCu
Hi all,

I've recently set up a Nextcloud instance on an LXC container and changed the background task setting to a system Cron job. Unfortunately, the documented setting on [1] did not work on my system.

After fiddling around and searching the web, I've found a webpage that states a missing parameter in the documentation [2]. Interestingly, the setting is documented in the page about the *caching configuration* [3].

I will open a pull request to clarify this setting on the Cron page, as this is much easier to find IMO.

[1] https://docs.nextcloud.com/server/16/admin_manual/configuration_server/background_jobs_configuration.html#cron
[2] https://linuxnews.de/2021/07/nextcloud-22-deaktiviert-php-cronjobs/ [German]
[3] https://docs.nextcloud.com/server/21/admin_manual/configuration_server/caching_configuration.html#id1

### PR DESCRIPTION
**Pull request by maxkratz**
Closes #7051.

This adds a note about the parameter `--define apc.enable_cli=1` that might be necessary for some newer instances. For more information, please refer to the linked issue #7000.

### CODE REVIEW

**Comment by kesselb** [comment]
Hey Max :wave: ,

thanks for your pull request. What is `</caching_configuration>`? I don't think that works to cross reference another topic. Would you mind to remove it?

**Comment by maxkratz** [comment]
Hi @kesselb!

Thank you for taking a look at my pull request.

> What is </caching_configuration>? I don't think that works to cross reference another topic.

At least on my machine it works and gives me a clickable link to the topic of *caching_configuration*. (This is the section in which the `--define apc.enable_cli=1` hint is originally introduced.)

Can you please try it out if it also works on your build system :)?

**Comment by kesselb** [comment]
```
Please refer to :doc:`./caching_configuration` (section APCu).
```

We usually cross reference pages like above. The main advantage is that the page title is pulled in. Would you mind to update your pr accordingly?

**Comment by maxkratz** [comment]
> ```
> Please refer to :doc:`./caching_configuration` (section APCu).
> ```
> 
> We usually cross reference pages like above. The main advantage is that the page title is pulled in. Would you mind to update your pr accordingly?

Alright, I've changed the cross-reference as you requested :).

**Review by kesselb — APPROVED** [review]

**Comment by kesselb** [comment]
Thanks :+1:

**Pull request merged**
