### PR TITLE
update text and formatting

### PR DESCRIPTION
**Pull request by enoch85**
cc @jospoortvliet @MorrisJobke 

Updating changes made in https://github.com/nextcloud/documentation/pull/921

### CODE REVIEW

**Comment by enoch85** [comment]
OK to merge?

**Comment by jospoortvliet** [comment]
One change. We either call both VM's official, or neither... Both are well maintained and have been for a while, just like our Docker image and Snap they're as official as it gets in our community. If you can change the wording so that they are considered equal somehow, then the rest is fine :+1:

**Comment by enoch85** [comment]
Please approve and merge. Please also SQUASH the commits.

**Comment by MorrisJobke** [comment]
stable15 9e825e9d

**Comment by MorrisJobke** [comment]
> stable15 [9e825e9](https://github.com/nextcloud/documentation/commit/9e825e9d3ef7c4251e9bbc425c60dfbce739e0ae)

Reverted because I realized, that this was already back ported and fixed by me. Revert is in 4d92be5c

**Pull request merged**
