### PR TITLE
Update tutorial.rst

### PR DESCRIPTION
**Pull request by DaphneMuller**
Added a link to the new tutorials

Signed-off-by: Daphne Muller <86835268+DaphneMuller@users.noreply.github.com>

### CODE REVIEW

**Comment by tflidd** [comment]
Nice to have updates on the tutorial. But creating yet another source for documentation is a bit strange. It's just text, so it should be possible to get in the current documentation.... Here everything is on followed up by git, we can handle different versions, allow everybody to contribute.

Is it the markup that makes it easier? Or the structure on the current documentation?

**Comment by DaphneMuller** [comment]
At the moment the tutorials are hosted on a shared folder on cloud.nextcloud.com. We made this choice because this is the easiest and quickest way for us right now to develop and improve the tutorials fast. When they are more stable we will certainly look into a nicer and more permanent publishing solution. I am not sure if the developer documentation is an appropriate place to host tutorials, but maybe it is, I have not made up my mind yet, and it doesn't really matter in the end as long as the resources are easy to find. This is why I added this link to this page so that everyone can find the resources. I see no issue right now.

**Review by bigcat88 — APPROVED** [review]
Ready to merge, now this PR does not add new warnings/errors.

**Review by andrey18106 — COMMENTED** [review]
Looks good to me

**Pull request merged**
