### PR TITLE
We have two VM's, add Univention.

### PR DESCRIPTION
**Pull request by jospoortvliet**
Of course, we should have had both options here from the beginning... :see_no_evil:

### CODE REVIEW

**Comment by MorrisJobke** [comment]
stable13 a03437da
stable14 b19712c7

**Comment by enoch85** [comment]
Fine with me, but would be nice if you added SME as on the downloads page. :)

**Comment by jospoortvliet** [comment]
I called it SMB instead of SME, sorry - otherwise, it's there, right?

**Comment by enoch85** [comment]
Yes otherwise it's correct. I will make some more changes and I can change it to SME in the same PR.

**Comment by jospoortvliet** [comment]
ok!

**Pull request merged**
