### PR TITLE
Add note about known to work hardware tokens

### PR DESCRIPTION
**Pull request by alex-nitrokey**

### CODE REVIEW

**Comment by skjnldsv** [comment]
Cc @christophWurst

**Comment by jans23** [comment]
@rullzer What do you think?

**Comment by alex-nitrokey** [comment]
> If we want to have this it should be at https://github.com/nextcloud/twofactor_u2f#u2f-second-factor-provider-for-nextcloud, similar to the apps at https://github.com/nextcloud/twofactor_totp

Do you mean adding this information to said repos additionally or instead of adding it here?

**Comment by tflidd** [comment]
FIDO/U2F is not enough of a standard that we can suppose in general that it works?

For TOTP based, I'd like to see more so we do not just promote one product (then perhaps point out devices with open design).

**Comment by ChristophWurst** [comment]
> Do you mean adding this information to said repos additionally or instead of adding it here?

We can add it as you proposed, but it's not 100% fitting IMO as the manual does not cover u2f otherwise. Hence I suggested adding it to the twofactor_u2f repo readme. We can also do both if you want :)

**Comment by jans23** [comment]
Looking at our partnership to promote the usage of 2FA, adding both would be great.

**Comment by jospoortvliet** [comment]
@jans23 - if you modify the PR to add it to both, if that's OK with @ChristophWurst  - we can merge ;-)

**Comment by alex-nitrokey** [comment]
[OTP README PR](https://github.com/nextcloud/twofactor_totp/pull/720)
[U2F README PR](https://github.com/nextcloud/twofactor_u2f/pull/569)

Is this what you were thinking of?

**Pull request merged**
