### PR TITLE
Update example_centos.rst

### PR DESCRIPTION
**Pull request by bkmgit**
Slight update of #1908

Indicate for PHP 74 in modules
Use dnf instead of yum

### CODE REVIEW

**Comment by bkmgit** [comment]
Performing further checks after finding an error

**Comment by juliushaertl** [comment]
> Performing further checks after finding an error

Anything left to do from your side?

**Comment by bkmgit** [comment]
I checked, it seems to work, so can merge.

**Comment by bkmgit** [comment]
Seems like signoff needs to be done on each commit through web interface, https://community.openhab.org/t/dco-check-signing-off-with-github-web-editor-explanation/83330 hopefully can still approve.

**Comment by bkmgit** [comment]
Would it be worth adding some information about signing off in the README https://github.com/nextcloud/documentation/blob/master/README.rst
See also https://probot.github.io/apps/dco/

**Pull request merged**
