### PR TITLE
Add User Manual Pt-br

### PR DESCRIPTION
**Pull request by sirpresident**
Adding the first version of the user manual Nextcloud.

### CODE REVIEW

**Comment by skjnldsv** [comment]
Hello @sirpresident and thanks for your pr! This is a tremendous amount of work!! :+1: 

We currently only have en and de manuals, and I'm not sure what position we want to take regarding translations. Should we create dedicated directories like you did? There is a French team who forked the repo to translate it as well. We need to discuss this I guess! :)

@nextcloud/documentation what do you think?

**Comment by MorrisJobke** [comment]
Thanks a lot. I guess @jospoortvliet had in the past some ideas how to work on this.

**Comment by sirpresident** [comment]
> Hello @sirpresident and thanks for your pr! This is a tremendous amount of work!! +1
> 
> We currently only have en and de manuals, and I'm not sure what position we want to take regarding translations. Should we create dedicated directories like you did? There is a French team who forked the repo to translate it as well. We need to discuss this I guess! :)
> 
> @nextcloud/documentation what do you think?

It really worked hard, but it was satisfactory for me to contribute Nextcloud! Anything I'm at your disposal!

**Comment by jospoortvliet** [comment]
Nice work there! I'm also not sure what to do here, forking the repo I think makes it nearly impossible to keep up, but how else to do I don't really know... Then again, if we stick to the end user manual, it doesn't change as regularly as the admin manual, it might work.

**Comment by sirpresident** [comment]
> Nice work there! I'm also not sure what to do here, forking the repo I think makes it nearly impossible to keep up, but how else to do I don't really know... Then again, if we stick to the end user manual, it doesn't change as regularly as the admin manual, it might work.

Nice!  
I will create another PR, for this translation in a dedicated branch, this way it can facilitate the visualization of the modified files before a possible merge

**Pull request closed without merging**
