### PR TITLE
Update min stable: 15 - 17

### PR DESCRIPTION
**Pull request by skjnldsv**
Latest stable is now 17

@blizzz @rullzer please create the new alias to the stable17 docs in the documentation server :)

### CODE REVIEW

**Comment by skjnldsv** [comment]
nextcloud 14 is no longer publicly maintained

**Comment by blizzz** [comment]
> please create the new alias to the stable17 docs in the documentation server :)

@rullzer please do and/or tell me where the magic is hidden

**Comment by skjnldsv** [comment]
@blizzz iirc there is just a new task to add to cron, and you need to update the nginx aliases of `stable` and `latest`

**Comment by blizzz** [comment]
@skjnldsv when i look at 'stable' and not 'latest' it suddenly all makes sense :man_facepalming: 

Well, but, for the cron job. There's nothing related.

**Comment by skjnldsv** [comment]
No idea then :)
Ask Morris :p

**Pull request merged**
