### PR TITLE
[stable10] update supported apps

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @karlitschek @jospoortvliet @nickvergessen @oparoz

### CODE REVIEW

**Comment by mar1u5** [comment]
What about "Theming"?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/documentation/issues/75#issuecomment-235520884

+ lets wait for frank to confirm

**Comment by MorrisJobke** [comment]
> What about "Theming"?

Damn. I missed that. I will create a new PR :) Thanks for spotting.

**Comment by karlitschek** [comment]
👍

**Comment by MorrisJobke** [comment]
I updated the list.

**Comment by mar1u5** [comment]
:+1:

**Pull request merged**
