### PR TITLE
Update nginx-subdir.conf.sample &  nginx-root.conf.sample

### PR DESCRIPTION
**Pull request by noci2012**
prevent 405 error combined with pretty URL's

### ☑️ Resolves

* Issue with f.e. shifts (shiftplan)  that uses URL:
https://server/admin/settings     with PUT
location /   (without proxy_pass) returns error 405 on PUT/POST...

Solution a redirect in case of 405 errors.

Example patched.

### CODE REVIEW

**Comment by noci2012** [comment]
Not sure this is the way to go now, it breaks some other things, some discussion appreciated.

**Comment by kesselb** [comment]
Thanks :+1: 

I fail to understand your change. 

Did you discuss this change with the shifts developers?

**Comment by noci2012** [comment]
never mind,.
There is a class of apps that doesn't work...
As there is a redirect to a directory. Shift plan is such an app.

**Comment by noci2012** [comment]
This is the issue btw.
https://www.bonbon.io/articles/how-to-enable-post-to-static-pages-running-via-nginx

**Pull request closed without merging**
