### PR TITLE
Proxy notation hints

### PR DESCRIPTION
**Pull request by wiswedel**
Added hints to the different allowed notations for trusted proxies

Signed-off-by: Sascha Wiswedel <sascha.wiswedel@nextcloud.com>

### CODE REVIEW

**Comment by skjnldsv** [comment]
Sure :)
@wiswedel backports?

**Comment by wiswedel** [comment]
> Sure :)
> @wiswedel backports?

@skjnldsv: Seems to work since 15: https://github.com/nextcloud/server/pull/12036

**Comment by skjnldsv** [comment]
@wiswedel a bit of magic, yu can trigger an automated backport by doing like this:

/backport to stable15

**Comment by skjnldsv** [comment]
(wrong close button ;) )

/backport to stable16

**Comment by wiswedel** [comment]
> @wiswedel a bit of magic, yu can trigger an automated backport by doing like this:

@skjnldsv Awesome. Thx!

**Pull request merged**
