### PR TITLE
Use versionadded directive for added OCP events

### PR DESCRIPTION
**Pull request by ChristophWurst**
Why write it out when sphinx can write the text for us?

| Before | After |
|---|---|
| Bildschirmfoto vom 2022-11-14 14-38-20 | Bildschirmfoto vom 2022-11-14 14-38-07 |

### CODE REVIEW

**Comment by ChristophWurst** [comment]
I'm not backporting further but only to 25 so we have this in the latest *stable* docs.

**Comment by kesselb** [comment]
Awesome :+1:

**Review by juliushaertl — APPROVED** [review]

**Comment by MorrisJobke** [comment]
🥳 Nice one1

**Pull request merged**
