### PR TITLE
Content list documentation

### PR DESCRIPTION
**Pull request by skjnldsv**
After https://github.com/nextcloud/server/pull/7195

Please review!
Is it clear enough? :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice! :) Should we specifically say something about that we recommend using the `app-content-list-item-icon` for profile photos, or favicons, etc?

cc @nextcloud/designers

**Comment by skjnldsv** [comment]
@jancborchardt yes, it's a requirement :)

**Comment by juliushaertl** [comment]
Looks good to me. Just the screenshot besides the first code snippet should be moved above, because it currently shrinks the code block so that it is quite hard to read.

**Comment by skjnldsv** [comment]
@juliushaertl I'll remove the inline image code block

**Comment by jancborchardt** [comment]
Aaawesome! :) Great job with the docs as always @skjnldsv

**Comment by skjnldsv** [comment]
Thank Jan! 🤗

**Pull request merged**
