### PR TITLE
Makes the transifex build automatic.

### LINKED ISSUE #216: Documentation update and translation with transifex
Would appreciate an update of the documentation and translation via transifex.

Major goal is an update of the documentation.
Minor goal is transifex translation.

Would start with an update of the english documentation and then at least create a german translation via transifex.
As I am new to nextcloud i would appreciate every help i can get.
I assume that this should be handled with high priority as it helps spreading nextcloud to users and could ease handle and  supporting effort.

### PR DESCRIPTION
**Pull request by pierreozoux**
The build is failing because we need to add transfiex credentials to the bot.

Can somebody help with that? I have no access to travis.

Closes #216

### CODE REVIEW

**Comment by pierreozoux** [comment]
Can we get this moving? Who can I help?

**Comment by dhebert91** [comment]
I'am also interested to have the french user manual integrated on https://docs.nextcloud.com/. 
We have done it there: https://www.transifex.com/nextcloud/nextcloud-user-documentation/ and we are waiting for somebody to help us to integrate it.
The result is there: https://doc-nextcloud-fr.indie.host/com/fr/

**Comment by skjnldsv** [comment]
@pierreozoux can you rebase? :)

**Comment by jospoortvliet** [comment]
> I'am also interested to have the french user manual integrated on https://docs.nextcloud.com/.
> We have done it there: https://www.transifex.com/nextcloud/nextcloud-user-documentation/ and we are waiting for somebody to help us to integrate it.
> The result is there: https://doc-nextcloud-fr.indie.host/com/fr/

That is very cool! I think @morrisjobke will likely be able to figure out how to have the docs on docs.nextcloud.com translated once the work from @pierreozoux is integrated.

**Pull request closed without merging**
