### PR TITLE
fix visual issue with section 9

### LINKED ISSUE #270: Nextcloud 11 documentation fix needed
https://github.com/nextcloud/documentation/blob/stable11/admin_manual/maintenance/manual_upgrade.rst

```
Section 9 Adjust file ownership and permissions

   chown -R www-data:www-data nextcloud 
   find nextcloud/ -type d -exec chmod 750 {} ;
   find nextcloud/ -type f -exec chmod 640 {} ;
```
is rendered incorrectly:

20161213-23 29 15_auswahl

Yes, I tried to fix this, but without success (I got crazy by editing this rst file...)

### PR DESCRIPTION
**Pull request by jospoortvliet**
fixes #270

### CODE REVIEW

**Comment by Wikinaut** [comment]
Layout: fine

Content: is "\;" at the end of the two lines correct ??

**Comment by Wikinaut** [comment]
@jospoortvliet sorry:

Layout: is fine

Content: is `\;` at the end of the two lines correct ??

**Comment by Wikinaut** [comment]
@jospoortvliet  `\;` appears to be correct

**Comment by MorrisJobke** [comment]
👍

**Comment by MorrisJobke** [comment]
master: #280

**Pull request merged**
