### PR TITLE
Optimize Android sync docs

### PR DESCRIPTION
**Pull request by MariusBluem**
Signed-off-by: Marius Blüm <marius@lineone.io>

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
I would also add the other way around:
- open android app
- go to settings
- click on "synchronize calendar & contact"
--> dax x5 will be downloaded and server / username filled in, but password needs to be typed in again

**Comment by MorrisJobke** [comment]
@tobiasKaminsky Could you open a ticket for this?

**Pull request merged**
