### PR TITLE
Update security_setup_warnings.rst

### PR DESCRIPTION
**Pull request by jospoortvliet**
fix links :see_no_evil:

### CODE REVIEW

**Comment by jospoortvliet** [comment]
@MariusBluem @MorrisJobke sorry I screwed up my previous PR

**Comment by MariusBluem** [comment]
well... you did 😜 And I did not look close enough 🙈

**Comment by MorrisJobke** [comment]
stable11 91492ab
stable10 915294c

**Comment by jospoortvliet** [comment]
THANK YOU

**Pull request merged**
