### PR TITLE
Update the 'Migrating' page to include optional 'maintenance:data-fingerprint' command step.

### PR DESCRIPTION
**Pull request by allexzander**
Signed-off-by: alex-z <blackslayer4@gmail.com>

### CODE REVIEW

**Review by jospoortvliet — APPROVED** [review]
Looks good to me!

**Comment by jospoortvliet** [comment]
> does this not apply to older releases? I think we should backport

pretty sure, yes. But I don't know how to do backports, well, something with /backport or so, but 🙈

@allexzander this is relevant for all current releases, right?

**Comment by ChristophWurst** [comment]
This has to be done manually

**Pull request merged**
