### PR TITLE
Update recommended DBs

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by rullzer** [comment]
This list is also valid for stable17. So lets backport

**Comment by kesselb** [comment]
Something went wrong :see_no_evil:

**Comment by ChristophWurst** [comment]
> Something went wrong see_no_evil

Mind eleborating? :grinning:

**Comment by kesselb** [comment]
image


I already send a patch but forgot to mention this pr ;)

**Comment by ChristophWurst** [comment]
Ha! Didn't see that :)

**Pull request merged**
