### PR TITLE
Add a section "How to test ..."

### PR DESCRIPTION
**Pull request by MorrisJobke**
I had the idea that we should have a documentation page that lists environments that are a bit harder to setup (LDAP, Redis, Object Storage,...) and document how a test environment could be created.

Today I needed to install a Redis Cluster and searched for some projects that make the live easier there. 

@ChristophWurst @rullzer @blizzz @icewind1991 @jancborchardt @GretaD @tobiasKaminsky @juliushaertl @kesselb @skjnldsv Feedback welcome. We should also migrate the LDAP guide from the wiki to this page: https://github.com/nextcloud/server/wiki/How-to-test-LDAP%3F

### CODE REVIEW

**Comment by blizzz** [comment]
This makes sense. Perhaps we should split it up in subpages though, otherwise it'll get long quickly.

**Comment by skjnldsv** [comment]
Samba:
``` bash
mkdir samba
docker run -it -p 139:139 -p 445:445 -v ./samba:/smbmount dperson/samba -u "user;password" -s "public;/smbmount;yes;no;yes"
```
And you need the following config in your php container/setup:
https://github.com/skjnldsv/docker-nextcloud-dev/blob/b2950e00c7d111ed1c98652cffa25a81c0821777/Dockerfile#L92-L97

``` sh
# /etc/samba/smb.conf
[global]
client min protocol = SMB2
client max protocol = SMB3
hide dot files = no
```

**Comment by MorrisJobke** [comment]
> This makes sense. Perhaps we should split it up in subpages though, otherwise it'll get long quickly.

Yes, but as of now it's fine to have only one page.

**Comment by ChristophWurst** [comment]
# SAML setup with onelogin

* create dev account on onelogin.com
* log into onelogin.com
* create new app: SAML Test Connector (Advanced)
  * go to "Configuration"
      * Audience: https://localhost/apps/user_saml/saml/metadata
      * Recipient: https://localhost/apps/user_saml/saml/acs
      * ACS (Consumer) URL Validator: https://localhost/apps/user_saml/saml/acs
  * go to "Parameters"
    * Add "User.email" -> email (and add to assertion)
    * Add "User.FirstName" -> first name (and add to assertion)
    * Add "User.LastName" -> last name (and add to assertion)
* open Nextcloud SAML settings
  * Select SAML
  * Configure it according to https://portal.nextcloud.com/article/configuring-single-sign-on-10.html

**Comment by skjnldsv** [comment]
It could be awesome to have all-in-one docker that just need a start.
Even better an app for this than can run docker from php and pre-configure nextcloud :p

**Comment by MorrisJobke** [comment]
> It could be awesome to have all-in-one docker that just need a start.

That's not how docker works ... typically one process per container. All in one is just a master process that then spawns multiple others and it only has disadvantages when it comes to process management and failed processes, because that is what you then need to re-implement. `docker-compose.yml` is what you are looking for 😉

**Comment by skjnldsv** [comment]
Yes, I meant all-in one dockerS :p
A docker that is already ready for smb, one already ready for ldap, ect etc :)

**Comment by tobiasKaminsky** [comment]
May I just add a new section here?
Or create a new PR?

I want to add how to set up Collabora locally without SSL.

**Comment by skjnldsv** [comment]
Bump! :)

**Comment by tobiasKaminsky** [comment]
@skjnldsv @ChristophWurst can you add your both ideas directly to this PR?
Then we can review & merge

**Comment by juliushaertl** [comment]
Collabora part looks good @tobiasKaminsky :+1:

**Comment by tobiasKaminsky** [comment]
I added OnlyOffice

**Comment by tobiasKaminsky** [comment]
Currently no time to edit it, but:
OnlyOffice without ssl
- ignore ssl stuff
- forward 80 to 8888
- use it

**Comment by juliushaertl** [comment]
I've added the SAML and SMB docs mentioned and polished the layout a bit. I'd say let's get this in. We can always adjust/extend later.

**Pull request merged**
