### PR TITLE
Reorder nginx config sample

### PR DESCRIPTION
**Pull request by ChristianTacke**
Move the `root` directive more to the top. That way all the fields that need to be changed are in one place.

### CODE REVIEW

**Comment by ChristianTacke** [comment]
@kesselb (saw you doing triage in another PR):

Can you let me know, what I need to change/improve to get a review?

**Review by MichaIng — APPROVED** [review]

**Comment by ChristianTacke** [comment]
Should I rebase and force-push to restart the checks?

**Comment by MichaIng** [comment]
Yes please do so.

**Comment by ChristianTacke** [comment]
Okay, rebased, and force-pushed. Looks like a maintainer needs to approve the workflows?
>  3 workflows awaiting approval
> First-time contributors need a maintainer to approve running workflows.

**Comment by MichaIng** [comment]
A nice, a _simple_ organisation member like me can trigger the CI as well 🙂.

**Pull request merged**
