### PR TITLE
Update files versions documentations

### PR DESCRIPTION
**Pull request by artonge**
Before | After
-- | --
Screenshot from 2024-03-05 11-28-18 | Screenshot from 2024-03-05 11-27-44
Screenshot from 2024-03-05 11-28-51 | Screenshot from 2024-03-05 11-18-35

### CODE REVIEW

**Review by come-nc — APPROVED** [review]
:+1:

**Comment by artonge** [comment]
Up to 26

**Comment by artonge** [comment]
Ah, wait, not for the limitations notice

**Comment by artonge** [comment]
/backport ae5acaf9795ec8d790440b771063f95e2f969711 to stable28

**Comment by artonge** [comment]
/backport ae5acaf9795ec8d790440b771063f95e2f969711 to stable27

**Comment by artonge** [comment]
/backport ae5acaf9795ec8d790440b771063f95e2f969711 to stable26

**Comment by artonge** [comment]
/backport 17058599f3f8128779ce313b41f81d11ef409999 to stable28

**Comment by artonge** [comment]
/backport ae5acaf9795ec8d790440b771063f95e2f969711 to stable28

**Pull request merged**
