### PR TITLE
updated EOL for MySQL and MariaDB

### PR DESCRIPTION
**Pull request by wiswedel**
Signed-off-by: Sascha Wiswedel <sascha.wiswedel@nextcloud.com>

### CODE REVIEW

**Comment by wiswedel** [comment]
semi-manual backport necessary because https://github.com/nextcloud/documentation/pull/1821 wasn't backported

**Comment by skjnldsv** [comment]
I'm actually not sure, there was some compatibility fixes for newest mysql/mariadb but for 19, not idea if backported :)

**Comment by wiswedel** [comment]
> I'm actually not sure, there was some compatibility fixes for newest mysql/mariadb but for 19, not idea if backported :)

Even 10.2 is already 3 years old, should be fine for NC 16-18.

**Comment by nickvergessen** [comment]
> I'm actually not sure, there was some compatibility fixes for newest mysql/mariadb but for 19, not idea if backported :)

mariadb 10.4+ and mysql 8+

but I think we even backported them until 17, only 16 does not work with 8/10.4

**Comment by nickvergessen** [comment]
Ref https://github.com/nextcloud/server/pull/19328

**Comment by nickvergessen** [comment]
Btw what about master?

**Comment by wiswedel** [comment]
> Btw what about master?

That's been taken care of by @rullzer already in https://github.com/nextcloud/documentation/pull/1821

**Comment by nickvergessen** [comment]
but 10.1 vs 10.2 is missing there

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/documentation/pull/1937 ah well

**Pull request merged**
