### PR TITLE
remove php-exif

### PR DESCRIPTION
**Pull request by jameskimmel**
### ☑️ Resolves

* not needed, since it is already enabled by default.

### CODE REVIEW

**Comment by tflidd** [comment]
I don't see that it is required by the default setup of Nextcloud:
https://docs.nextcloud.com/server/latest/admin_manual/installation/php_configuration.html

**Comment by jameskimmel** [comment]
> I don't see that it is required by the default setup of Nextcloud: https://docs.nextcloud.com/server/latest/admin_manual/installation/php_configuration.html

It isn't. But also if you wanna make use of it, there is no need to install the module.
Another possibility would be to add (included with PHP) like we did for the fileinfo module in the same doc.

**Comment by kesselb** [comment]
Thanks for your pull request :+1: 

How PHP is packaged depends on your operating system. It got better over the years and is now very similar for most distributions.

I usually check https://pkgs.org/download/php-exif for such questions. Ubuntu, Debian, Fedora and others bundle it with common. OpenSuse and Alpine have an extra package.

As there's no harm by listening php-exif here and an admin can always use `php -m|grep exif` to check if the module is there I would rather not merge it.

**Comment by jameskimmel** [comment]
That makes total sense. Sorry that I wasn't aware of how this is handled.
Thank you for taking the time to look at it!

**Pull request closed without merging**
