### PR TITLE
Add service discovery to reverse proxy doc

### PR DESCRIPTION
**Pull request by kesselb**

### CODE REVIEW

**Comment by kesselb** [comment]
@MorrisJobke could you share a screenshot of the final version? I can't build it locally.

**Comment by MorrisJobke** [comment]
> I can't build it locally.

Mind to troubleshot this?

I guess the install instructions are just way off.

Typically it consist of those steps:

1. Install `pipenv` - https://pipenv.readthedocs.io/en/latest/
2. Create a Python 2 environment (typically inside the documentation repo): `pipenv --two`
3. Change into the environment: `pipenv shell`
4. Install the dependencies `pip install -r requirements.txt`
5. Now you can use `make ...` to build all the stuff

@kesselb Mind to update the readme with that info?

**Comment by MorrisJobke** [comment]
> @kesselb Mind to update the readme with that info?

#1299

**Comment by MorrisJobke** [comment]
Bildschirmfoto 2019-03-12 um 10 22 53

**Comment by kesselb** [comment]
Ok. I hope someone from the community can share an example for nginx.

**Comment by MorrisJobke** [comment]
> Ok. I hope someone from the community can share an example for nginx.

It is already in the Nginx config: https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html?highlight=nginx#nextcloud-in-a-subdir-of-nginx

```nginx
    location = /.well-known/carddav {
      return 301 $scheme://$host/nextcloud/remote.php/dav;
    }
    location = /.well-known/caldav {
      return 301 $scheme://$host/nextcloud/remote.php/dav;
    }
```

**Pull request merged**
