### PR TITLE
feat(adminmanual): Amend upgrade notes about mailer changes in 26

### PR DESCRIPTION
**Pull request by kyteinsky**
### ☑️ Resolves

Update changelog of NC 26 to clarify email setup instructions and changes

### 🖼️ Screenshots

image

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by kyteinsky** [comment]
does not need to be backported to 26

**Comment by ChristophWurst** [comment]
indeed a weird situation because https://github.com/nextcloud/documentation/pull/10468 is only there for 27, not 26. ideally we bring this to 26, too, because admins will check https://docs.nextcloud.com/server/26/admin_manual/release_notes.html, not https://docs.nextcloud.com/server/27/admin_manual/release_notes/index.html#critical-changes

**Comment by kyteinsky** [comment]
sorry got a little confused there. Sure, I will open a PR soon.

**Comment by joshtrichards** [comment]
Thanks for expanding that note, @kyteinsky!

**Comment by kyteinsky** [comment]
All thanks to Anna and Christoph :D

**Pull request merged**
