### PR TITLE
Add ownCloud migration paths to the docs

### PR DESCRIPTION
**Pull request by nickvergessen**
Since the question arises quite often, lets add it to the docs.

@MorrisJobke @jospoortvliet 

> migrating_from_owncloud_ _nextcloud_12_server_administration_manual_12_documentation_-_2017-06-18_16 25 28

### CODE REVIEW

**Comment by MorrisJobke** [comment]
What about the migration script?

**Comment by nickvergessen** [comment]
Couldn't find anything useful with google where I could link to...

**Comment by MariusBluem** [comment]
What is with migrating from ownCloud 8.2 and older?
However: Why do we not mirror the guide from here: https://nextcloud.com/migration?

**Comment by nickvergessen** [comment]
Ah I forgot about that page

Not a fan of mirroring stuff... Maybe link from docs to there or the other way

**Comment by MariusBluem** [comment]
I‘d go with moving it to the documentation, and removing it from the homepage. I will do the same for CODE, since I don’t think it is a good idea to have such manuals on pages where non-technical enterprise users look at ;)

**Comment by jospoortvliet** [comment]
@MariusBluem we have to have some info on the migration on our website - as it is an important subject. We need to have some information on how, too - as in, a step by step like we have there now,because we have to show how easy it is. But we could simplify it and link to our documentation, yes.

**Comment by jospoortvliet** [comment]
Besides all that, this looks good :1st_place_medal: 

I would point out that using our updater is also possible, though. I promote that as the best way of doing this from our website and blog, now, I think our documentation should probably say the same.

**Comment by MorrisJobke** [comment]
stable12 3cc84478

**Pull request merged**
