### PR TITLE
Talk documentation

### PR DESCRIPTION
**Pull request by jospoortvliet**
I was just sick and tired of not having documentation for talk, so I made it ;-)

Signed-off-by: Jos Poortvliet <jospoortvliet@gmail.com>

### CODE REVIEW

**Comment by jospoortvliet** [comment]
I am not sure the locale and templates files had to change?!?! But sphinx did that... The real changes are in the Talk folder, of course, and the main index. I also fixed a missing index in Files, but otherwise I was a good boy and did stay within my Talk folder :D

**Comment by nickvergessen** [comment]
Minor wording changes needed:
- [ ] s/room/conversation
- [ ] Deck items are cards not tasks


From my POV it comes a bit early as we are still heavily juggling around the call view and conversation settings for moderators, so the screenshots will need updating soon, but might always happen.

**Comment by nickvergessen** [comment]
Mind to copy the talk/ folder, go back to master, make a new PR and then push the talk/ folder there?

**Comment by jospoortvliet** [comment]
> Minor wording changes needed:
> 
> * [ ]  s/room/conversation
Done  (in the new PR as you requested)

> * [ ]  Deck items are cards not tasks
Yeah, but who knows what a card is - we try to communicate about them as tasks, not cards. I think ppl will get this easier. Not everyone is familiar with kanban :(

> From my POV it comes a bit early as we are still heavily juggling around the call view and conversation settings for moderators, so the screenshots will need updating soon, but might always happen.

Yeah, I get that, and you're right, and I know you're making heavy changes just now. Then again Talk is in its 3rd year now, we can't wait forever ;-)

**Comment by jospoortvliet** [comment]
will make a new PR

**Pull request closed without merging**
