### PR TITLE
Update source_installation.rst

### PR DESCRIPTION
**Pull request by Dark-Schnitzel**
Wrong Package Name, should be php7.0-imagick instead of php-imagick

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Un Ubuntu 16.04:

```
$ sudo apt install php-imagick
Reading package lists... Done
Building dependency tree       
Reading state information... Done
php-imagick is already the newest version (3.4.0~rc6-1ubuntu3).
$ sudo apt install php7.0-imagick
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php7.0-imagick
```

**Comment by MorrisJobke** [comment]
Could you explain why it should be php7.0-imagick?

**Comment by Dark-Schnitzel** [comment]
Hello,
i have misread that this if for Ubuntu 16.04 only.
 Installing on Debian 8 with php7.0 ppa:
 apt install php-imagickPaketlisten werden gelesen... FertigAbhängigkeitsbaum wird aufgebaut.Statusinformationen werden eingelesen.... FertigE: Paket php-imagick kann nicht gefunden werden.root@Nextcloud-Server:/home/nextcloud# apt install php7.0-imagickPaketlisten werden gelesen... FertigAbhängigkeitsbaum wird aufgebaut.Statusinformationen werden eingelesen.... Fertigphp7.0-imagick ist schon die neueste Version.0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Maybe there could be a hint pointing this out for Debian Users that they need to insert ppa like this, with a Standard Debian  Installation you cant just follow the Documentation
1. Remove old php5 if used, list installed packages:First, list all installed old php 5.x packages, enter:
$ dpkg --list | grep php | awk '/^ii/{ print $2}'
To delete old php 5.6 packages, enter:
$ x="$(dpkg --list | grep php | awk '/^ii/{ print $2}')"
$ sudo apt-get --purge remove $x
2. If its a fresh Install or php was not used before add the Repository:$ sudo -s
# echo 'deb http://packages.dotdeb.org jessie all' >> /etc/apt/sources.list
# echo 'deb-src http://packages.dotdeb.org jessie all' >> /etc/apt/sources.list

3. Add GPG key for Repository and Update Cache$ cd /tmp
$ wget https://www.dotdeb.org/dotdeb.gpg
$ sudo apt-key add dotdeb.gpg
$ rm dotdeb.gpg
Refresh apt database to include new packages:
$ sudo apt-get update
4. Install php7.0 packets
(source: https://www.cyberciti.biz/faq/installing-php-7-on-debian-linux-8-jessie-wheezy-using-apt-get)
Maybe we could add Subsection with this Information like this: https://docs.nextcloud.com/server/11/admin_manual/installation/php_55_installation.html
Regards,

Henrik Rosenke


13. Mai 2017 23:47 von notifications@github.com:

**Comment by MorrisJobke** [comment]
That's the reason we say this is Ubuntu 16.04. for other distros you need to check out where to get the correct versions of php. Sorry

**Pull request closed without merging**
