### PR TITLE
Move some sections and rename headings

### LINKED ISSUE #984: Re-organize structure of "install steps" in admin manual
There is another idea in my head to better organize the admin manual (see screenshots in next comment):

* move "Server configuration"/"Server tuning" to "Installation"
* move "Server configuration"/"Hardening and security guidance" to "Installation"
* rename "Installation" to "Installation and server configuration" because it holds only the installation and configuration of the stack
* rename "Server configuration" to "Nextcloud configuration" because it holds then the configuration of Nextcloud itself

@rakekniven @tflidd @danielkesselberg @michag86 @hanserasmus @jasonbayton Does that make sense? I'm for myself often confused where to find what part. Especially the mix of Nextcloud config vs stack config (PHP, DB, webserver, ...) is confusing me.

bildschirmfoto 2018-11-30 um 19 00 54
bildschirmfoto 2018-11-30 um 19 00 59

Obviously also feedback from others like @nickvergessen @MariusBluem @jospoortvliet @rullzer @skjnldsv or @blizzz is welcome. (just to mention a few)

This re-org should also cause the web server to return the manual landing page in case one page is not available anymore. Currently it just shows a 404.

### PR DESCRIPTION
**Pull request by MorrisJobke**
Fixes #984 

Additionally to the described stuff there I also removed all the "configuration/configure" terms from the headings in the configuration section. 

Also I fixed some broken links that came from #980. Thus I would backport this whole PR.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @hanserasmus

**Comment by MorrisJobke** [comment]
I'm still not satisfied by the different installation pages but that needs to be tackled in a future PR.

**Comment by rullzer** [comment]
Lets do this and improve step by step.

**Pull request merged**
