### PR TITLE
Update release_schedule.rst

### PR DESCRIPTION
**Pull request by StefanZGit**
Sorry, forgot a useful comment: I updated the Release schedule and moved version 17 and 18 to the "Older versions" section and added version 20 and 21.

### CODE REVIEW

**Review by tflidd — APPROVED** [review]

**Comment by tflidd** [comment]
Thanks for the housekeeping. The main location for the release schedule is as well out of date: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
