### PR TITLE
Add warnings about scaling issues with ajax and webcron

### PR DESCRIPTION
**Pull request by nickvergessen**
Green sections have been added:
Bildschirmfoto von 2022-04-25 12-23-56

### CODE REVIEW

**Comment by szaimen** [comment]
@nickvergessen would it make sense to also add a warning to the admin overview if more than e.g. 5 users are present and webcron is used?
Same for ajax and one user?

**Comment by nickvergessen** [comment]
The red warning that jobs are not executed should be enough? e.g. screenshot from https://github.com/nextcloud/server/issues/31725

**Comment by szaimen** [comment]
> The red warning that jobs are not executed should be enough? e.g. screenshot from [nextcloud/server#31725](https://github.com/nextcloud/server/issues/31725)

does this also show up in the admin overview?

**Comment by nickvergessen** [comment]
> does this also show up in the admin overview?

I guess not. Feel free to add it then.

**Comment by szaimen** [comment]
> > does this also show up in the admin overview?
> 
> I guess not. Feel free to add it then.

will do, thanks :)

**Review by szaimen — APPROVED** [review]

**Pull request merged**
