### PR TITLE
Up minimum PHP version to 8.0 and maximum to 8.2

### PR DESCRIPTION
**Pull request by come-nc**
Drop 7.4 and add 8.2

For https://github.com/nextcloud/server/issues/34692

### CODE REVIEW

**Comment by come-nc** [comment]
Who knows enough about centos to update https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/example_centos.rst ?

**Comment by ChristophWurst** [comment]
> Who knows enough about centos to update https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/example_centos.rst ?

@AndrewwHummer @hanserasmus would anyone be able to help us out here?

**Review by nickvergessen — APPROVED** [review]

**Comment by come-nc** [comment]
> Would it be probably better to use PHP 8.2 in examples, just so that it does not need to be changed again when Nextcloud drops support for PHP 8.0? slightly_smiling_face

Could have, should have, will do next time.

I’m merging this, centos thing can be done in an other PR.

**Comment by ChristophWurst** [comment]
> I’m merging this, centos thing can be done in an other PR.

Open a ticket an assign 26 just so this isn't forgotten? thx

**Pull request merged**
