### PR TITLE
Update deprecated globals in 19

### PR DESCRIPTION
**Pull request by ChristophWurst**
Ref https://github.com/nextcloud/server/pull/19455
Ref https://github.com/nextcloud/server/pull/19346
Ref https://github.com/nextcloud/server/pull/15403

### CODE REVIEW

**Comment by korelstar** [comment]
This should be added to https://github.com/nextcloud/eslint-plugin/blob/master/lib/rules/no-deprecations.js , too.

**Comment by ChristophWurst** [comment]
Yeah, on my todo for this afternoon already :)

**Comment by ChristophWurst** [comment]
Okay, let's say next week :pray:

**Comment by ChristophWurst** [comment]
Done via https://www.npmjs.com/package/@nextcloud/eslint-plugin

**Pull request merged**
