### PR TITLE
Fix translation mistakes https://chiffrer.info/

### PR DESCRIPTION
**Pull request by lorettet**
Fixed common translation mistakes. On dit chiffrer, pas crypter ;) https://chiffrer.info/

### CODE REVIEW

**Comment by tflidd** [comment]
Translations are done in Transifex and not directly managed in github. Perhaps something to add to the default translations in French...

@rakekniven can you help?

**Comment by rakekniven** [comment]
Just wrote a message to a french reviewer.

@tflidd How about your french? ;-)

**Comment by ldmpub** [comment]
Hi,

On the principle, this "word change" is ok according to me ("crypter/é ; encryptage" banned and replaced by "chiffrer/é ; chiffrement".
But as far as I see in the translation file of this commit, **there are also a lot of "double space" between words**. These double spaces have not been added by @lorettet (= they were pre-existant) but I think its time to remove them ; except if they have good reasons to be there?

**Comment by rakekniven** [comment]
Hello @ldmpub , nice to see you over here.
Will you take over this issue and do necessary changes at Transifex?

**Comment by ldmpub** [comment]
@lorettet ; @all 

As far as I understand changes should be done here in transifex: https://www.transifex.com/nextcloud/nextcloud-user-documentation/translate/#fr/user-manual-locale-source-files-encrypting-files-pot--master/184482861

I would be pleased to welcome new french speaking persons willing to improved translations 👍 in this tool.

**Comment by rakekniven** [comment]
@ldmpub How about the status of this issue? Has this been adapted at Transifex?

**Comment by ldmpub** [comment]
Hi,

I had a look and it looks already done.

My 2 cents: due to this change, some words, like `chiffrement` (which stands for `encryption`) sounds ugly in french sentences ...

You can close this issue (surprisingly as assignee I can not do it by myself)

**Comment by rakekniven** [comment]
> My 2 cents: due to this change, some words, like `chiffrement` (which stands for `encryption`) sounds ugly in french sentences ...

You are a reviewer for french. So please adapt the strings to your needs. If it sounds ugly ... not good.

**Pull request closed without merging**
