### PR TITLE
this should (...) fix the header and footer.

### PR DESCRIPTION
**Pull request by jospoortvliet**
It is a seriously horrible hack but I've included the css, js and html of our front page so we get the same fancy header. Of course, if we move a single asset there (which happens a LOT) we break our docu so this should be modified to be stand-alone, which I'll do in another PR. I first want to fix the ownCloud look our docu page... That is terrible.

I also cleaned up a lot of stuff in the styles.css.

If this gets deployed as the Nc 13 documentation, built for user etc etc, it should work. Though the three themes (...) are confusing, I modified the com one, as I think that that is the one we use.

It works locally perfectly but of course - only $DEITY knows what will happen upon deployment, this index.html is black magic :see_no_evil: 
Signed-off-by: Jos Poortvliet <jospoortvliet@gmail.com>

Fixes https://github.com/nextcloud/documentation/issues/726

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @skjnldsv

**Comment by MorrisJobke** [comment]
Merge conflicts

**Comment by jospoortvliet** [comment]
Maybe @skjnldsv can test it locally - and we should deploy carefully (not just before going to bed or something or risk :dagger: )

**Comment by jospoortvliet** [comment]
Once this is in we can merge https://github.com/nextcloud/documentation/pull/732 too - which makes all assets static so we don't have to depend on our website (which is soon going to be a new site)

**Comment by jospoortvliet** [comment]
@skjnldsv I know it isn't pretty but the current look sucks and if this works for you too, let's deploy it and clean it up later please? Our Documentation page looks horrible.

**Comment by MorrisJobke** [comment]
backported to stable13: 59851ab8

**Pull request merged**
