### PR TITLE
Removed obsolete tokens

### PR DESCRIPTION
**Pull request by christianlupus**
Currently, there are some obsolete parameters in the workflow files. This should remove some error messages from the workflows annotations/checks. This is part of #7646.

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by ChristophWurst** [comment]
I guess we should backport this?

**Comment by christianlupus** [comment]
@ChristophWurst I think this might be a good idea as it is an issue with the GitHub action and not with the version of NC.

**Pull request merged**
