### PR TITLE
Corrected link. Now pointing to new Transifex sub project.

### PR DESCRIPTION
**Pull request by rakekniven**
Signed-off-by: rakekniven <mark.ziegler@rakekniven.de>

### CODE REVIEW

**Comment by jospoortvliet** [comment]
@skjnldsv this should be backported as the link that is currently live still points to the wrong place...

Also, @rakekniven where can we see the actual German docs? Is that not yet ready to go?

**Comment by rakekniven** [comment]
Hello @jospoortvliet , where are all other languages available?
https://docs.nextcloud.com/ has not language switcher. Who knows some details?

**Comment by skjnldsv** [comment]
Only latest (20) have the translations, too complicated to backport

**Comment by skjnldsv** [comment]
But https://docs.nextcloud.com/server/latest/user_manual/ is down, I pinged the relevant people

**Comment by rakekniven** [comment]
Not down, not available, or?

https://docs.nextcloud.com/server/stable/user_manual/ works.

**Pull request merged**
