### PR TITLE
Fix traefik v1 example

### PR DESCRIPTION
**Pull request by FlorentPoinsaut**
We need to escape $ char in traefik v1 label otherwise this error occurs:
`ERROR: Invalid interpolation format for "labels" option in service "web": "https://$1/remote.php/dav/"`

### CODE REVIEW

**Comment by kesselb** [comment]
cc @mrtumnus @pauvos what do you think?

**Comment by mrtumnus** [comment]
I can't speak to the docker tag example, only to the toml portion.  Assuming the intent of the "?:" is to prevent regex capture of the "(cal|card)" group, looks good to me.

**Comment by kesselb** [comment]
> Assuming the intent of the "?:" is to prevent regex capture of the "(cal|card)" group, looks good to me.

Yeah `?:` makes it a non capturing group.

**Review by pauvos — COMMENTED** [review]
Hi there. I can't test the changes since i moved to k3s/traefikv2, but they look plausible.

For consistency we should probably change the v2 Middleware example as well:

```diff
spec:
  redirectRegex:
    permanent: true
-   regex: https://(.*)/.well-known/(card|cal)dav
+   regex: https://(.*)/.well-known/(?:card|cal)dav
-   replacement: https://${1}/remote.php/dav/
+   replacement: https://${1}/remote.php/dav # trailing slash is unnecessary
```

```sh
$ curl -I https://nextcloud.example.org/.well-known/carddav/something
HTTP/2 308 
location: https://nextcloud.example.org/remote.php/dav/something
```

Works on my machine!  :+1:

**Comment by kesselb** [comment]
Thanks :+1:

**Comment by kesselb** [comment]
@szaimen can you merge this one? I guess it's fine to ignore the missing build.

**Comment by FlorentPoinsaut** [comment]
Hello,
Thanks everybody for you feedbacks.
I removed trailing slash, added traefik v2 Docker label example and homogenized the examples.

**Review by kesselb — APPROVED** [review]
Thank you very much :+1:

**Comment by kesselb** [comment]
Sorry it took so long :see_no_evil:

**Comment by FlorentPoinsaut** [comment]
Don't worry about it.
Thank you for this merge @kesselb

**Pull request merged**
