### PR TITLE
Update SFTP description

### LINKED ISSUE #1494: SFTP is not ftp over ssh tunnel
https://docs.nextcloud.com/server/stable/admin_manual/configuration_files/external_storage/sftp.html
Says: "Nextcloud’s SFTP (FTP over an SSH tunnel) "

However,

https://en.wikipedia.org/wiki/SSH_File_Transfer_Protocol
Says: “SFTP is not FTP run over SSH, but rather a new protocol designed from the ground up by the IETF ECSH working group. It is sometimes confused with Simple File Transfer Protocol.”

This was corroborated on:
https://help.nextcloud.com/t/sftp-documentation/54930

### PR DESCRIPTION
**Pull request by mactrent**
Fix #1494

### CODE REVIEW

**Comment by tflidd** [comment]
backport to all previous version? They have the same error...

**Comment by skjnldsv** [comment]
Sure!

**Comment by mekineer** [comment]
Nextcloud's SFTP backend supports both password and public key authentication.
SFTP is not FTP run over SSH, but rather a new protocol designed from scratch
by IETF. The SFTP protocol allows for a range of operations on remote files,
engaging the remote file system as if it were native.

In setting up SFTP on Nextcloud, the **Host** field is required; a port can be
specified as part of the **Host** field in the following format:
``hostname.domain:port``. The default port is 22 (SSH).

**Pull request merged**
