### PR TITLE
chore(readme_styleFix): fix styling of the readme under build steps

### PR DESCRIPTION
**Pull request by abhay-bharat**
### ☑️ Resolves

* Fix #…

### 🖼️ Screenshots

- This is the fix for the readme style, where the instructions is provided for build and install.
- Making the instructions more readable and easy to understand.

### CODE REVIEW

**Comment by joshtrichards** [comment]
Hi @abhay-bharat - First, thanks for the contribution! Second, can you sign your commit?

https://github.com/nextcloud/documentation/pull/11903/checks?check_run_id=26071221652

**Comment by abhay-bharat** [comment]
Hi @joshtrichards - Thank you reviewing the changes. I have signed-off the commit, can you please review it again.

**Review by joshtrichards — APPROVED** [review]

**Comment by joshtrichards** [comment]
Done. It's live :)

**Comment by abhay-bharat** [comment]
Thank you!

**Pull request merged**
