### PR TITLE
Update encryption_migration.rst

### PR DESCRIPTION
**Pull request by andyxheli**
Signed-off-by: Andrea Xheli axheli@axtsolutions.com

### CODE REVIEW

**Review by jospoortvliet — APPROVED** [review]
works for me. Have to squash these commits a bit, though, but that can be done on merge...

**Comment by jospoortvliet** [comment]
Sorry it took so long, Andy!!! But it is in now ;-)

**Comment by jospoortvliet** [comment]
lol bot doesn't want to backport 🚀

**Comment by andyxheli** [comment]
@jospoortvliet Not a problem at all. Thank you for reviewing and approving :) Have a nice reset of your day.

**Pull request merged**
