### PR TITLE
enh(admin_manual/ai): Add context_chat

### PR DESCRIPTION
**Pull request by marcelklehr**
### 🖼️ Screenshots

image

### CODE REVIEW

**Review by DaphneMuller — APPROVED** [review]
thank you!

**Comment by marcelklehr** [comment]
@jospoortvliet Anything else we should add here?

**Review by kyteinsky — APPROVED** [review]
lgtm :tada:

**Comment by jospoortvliet** [comment]
> @jospoortvliet Anything else we should add here?

looks good imho. Once it's stable we can put in more details about the how and what!

**Pull request merged**
