### PR TITLE
Update system requirements - PHP 7.2 does not work

### PR DESCRIPTION
**Pull request by saper**
As per 12.0.1 changelog and https://github.com/nextcloud/server/pull/5793

### CODE REVIEW

**Comment by tflidd** [comment]
Once you are at it, you could fix it here as well:
https://docs.nextcloud.com/server/12/admin_manual/installation/deployment_recommendations.html

**Comment by MorrisJobke** [comment]
> Once you are at it, you could fix it here as well:
> https://docs.nextcloud.com/server/12/admin_manual/installation/deployment_recommendations.html

I guess it is okay there, because you will notice it on installation quite fast ;)

**Comment by MorrisJobke** [comment]
stable11 3fa54f7f

**Comment by MorrisJobke** [comment]
stable10 681f3346

**Pull request merged**
