### PR TITLE
Improve side menu layout

### PR DESCRIPTION
**Pull request by MorrisJobke**
Before:

bildschirmfoto 2016-12-08 um 11 12 48
bildschirmfoto 2016-12-08 um 11 12 45

After:

bildschirmfoto 2016-12-08 um 11 11 49
bildschirmfoto 2016-12-08 um 11 11 36

cc @nextcloud/designers

### CODE REVIEW

**Comment by MorrisJobke** [comment]
This also makes proper usage of the space in the sidebar. Before there was a lot of whitespace and the headings got wrapped quite often.

**Comment by MorrisJobke** [comment]
I also adapted the inline documentation that is then shipped in the release:

Before:
bildschirmfoto 2016-12-08 um 11 38 29

After:
bildschirmfoto 2016-12-08 um 11 38 09

**Comment by eppfel** [comment]
I like the border separators, but the `active` item rounded and left border is visually off-putting.
I like the inline documentation highlight. Maybe use it, but only color the background of current level and not all sub-levels? Just an idea. Especially, because in the inline docs the active highlight left-border is not really visual anymore.

**Comment by MorrisJobke** [comment]
> I like the border separators, but the active item rounded and left border is visually off-putting.
> I like the inline documentation highlight. Maybe use it, but only color the background of current level and not all sub-levels? Just an idea. Especially, because in the inline docs the active highlight left-border is not really visual anymore.

I tried this one, but it's kind of tricky - I just want to do a first step to make the sidebar more readable.

@eppfel Feel free to add some CSS rules, but I don't want to change the whole CSS and add JS for this little thing here ;)

**Comment by LukasReschke** [comment]
Looks way better than before. 👍

**Comment by skjnldsv** [comment]
👍

**Comment by MariusBluem** [comment]
Mind go ahead with #244 @MorrisJobke 🤔😅

**Pull request merged**
